/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CadastraAlteraFornecedor.java
 *
 * Created on 26/05/2011, 00:51:40
 */
package br.com.locadora.view;

import br.com.locadora.conexao.InterfacePool;
import br.com.locadora.conexao.Pool;
import br.com.locadora.model.bean.AcessoUsuario;
import br.com.locadora.model.dao.FornecedorDAO;
import br.com.locadora.model.bean.Fornecedor;
import br.com.locadora.model.bean.LogInfo;
import br.com.locadora.model.dao.LogInfoDAO;
import br.com.locadora.util.LimitadorTexto;
import br.com.locadora.util.TemaInterface;
import br.com.locadora.util.ValidaCnpj;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author ALENCAR
 */
public class CadastraAlteraFornecedor extends javax.swing.JFrame {

    public MenuFornecedor janelapai;
    public ConsultaFornecedorSaida janelapai2;
    public MaskFormatter formatoCNPJ, formatoTelefone, telefoneVendedor;
    public AcessoUsuario acesso;
    public FornecedorDAO fornecedorDAO;
    public InterfacePool pool;
    public Fornecedor fornecedor;

    /**
     * Creates new form FornecedorCadastroGUI
     */
    public CadastraAlteraFornecedor() {
        initComponents();
        TemaInterface.getInterface(this);
        this.setTitle("Cadastrando Fornecedor");
        janelapai = null;
    }

    public CadastraAlteraFornecedor(Fornecedor fornecedor) {
        this.fornecedor = fornecedor;
        initComponents();
        TemaInterface.getInterface(this);
        this.setTitle("Alterando Fornecedor");                
        jtf_codigo_fornecedor.setText(String.valueOf(fornecedor.getCodigo_fornecedor()));
        jtf_razao_social.setText(fornecedor.getRazao_social());
        jtf_nome_fantasia.setText(fornecedor.getNome_fantasia());
        jtf_endereco.setText(fornecedor.getEndereço());
        jtf_bairro.setText(fornecedor.getBairro());
        jtf_complemento.setText(fornecedor.getComplemento());
        jtf_cidade.setText(fornecedor.getCidade());
        jtf_estado.setText(fornecedor.getEstado());
        jftf_cnpj.setText(fornecedor.getCnpj());        
        jftf_telefone.setText(fornecedor.getTelefone());
        jftf_fax.setText(fornecedor.getFax());
        jtf_nome_vendedor.setText(fornecedor.getNome_vendedor());
        jftf_tel_vendedor.setText(fornecedor.getTel_vendedor());
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jb_salvar = new javax.swing.JButton();
        jb_cancelar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        try
        {
            formatoTelefone = new MaskFormatter("(##)####-####");
        }
        catch (Exception erro)
        {
            JOptionPane.showMessageDialog(null,"Não foi possivel setar");
        }
        jftf_telefone = new JFormattedTextField(formatoTelefone);
        jLabel7 = new javax.swing.JLabel();
        jtf_nome_fantasia = new javax.swing.JTextField(new LimitadorTexto(50), "",10);
        jtf_cidade = new javax.swing.JTextField(new LimitadorTexto(50), "",10);
        jtf_estado = new javax.swing.JTextField(new LimitadorTexto(50), "",10);
        try
        {
            formatoTelefone = new MaskFormatter("(##)####-####");
        }
        catch (Exception erro)
        {
            JOptionPane.showMessageDialog(null,"Não foi possivel setar");
        }
        jftf_tel_vendedor = new JFormattedTextField(formatoTelefone);
        jLabel15 = new javax.swing.JLabel();
        jtf_endereco = new javax.swing.JTextField(new LimitadorTexto(50), "",10);
        jtf_nome_vendedor = new javax.swing.JTextField(new LimitadorTexto(50), "",10);
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        try  {      
            formatoCNPJ = new MaskFormatter("##.###.###/####.##");  
        } 
        catch (Exception erro)  
        {    
            JOptionPane.showMessageDialog(null,"Não foi possivel setar");  
        }
        jftf_cnpj = new JFormattedTextField(formatoCNPJ);
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        try
        {
            formatoTelefone = new MaskFormatter("(##)####-####");
        }
        catch (Exception erro)
        {
            JOptionPane.showMessageDialog(null,"Não foi possivel setar");
        }
        jftf_fax = new JFormattedTextField(formatoTelefone);
        jLabel8 = new javax.swing.JLabel();
        jtf_codigo_fornecedor = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jtf_bairro = new javax.swing.JTextField(new LimitadorTexto(50), "",10);
        jLabel18 = new javax.swing.JLabel();
        jtf_complemento = new javax.swing.JTextField(new LimitadorTexto(50), "",10);
        jLabel16 = new javax.swing.JLabel();
        jtf_razao_social = new javax.swing.JTextField(new LimitadorTexto(50), "",10);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrando Fornecedor");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jb_salvar.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jb_salvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/locadora/image/save.png"))); // NOI18N
        jb_salvar.setText("Salvar");
        jb_salvar.setName("jb_salvar"); // NOI18N
        jb_salvar.setPreferredSize(new java.awt.Dimension(100, 40));
        jb_salvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_salvarMouseClicked(evt);
            }
        });
        jb_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_salvarActionPerformed(evt);
            }
        });
        jb_salvar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jb_salvarKeyPressed(evt);
            }
        });

        jb_cancelar.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jb_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/locadora/image/sair.png"))); // NOI18N
        jb_cancelar.setText("Sair");
        jb_cancelar.setName("jb_cancelar"); // NOI18N
        jb_cancelar.setPreferredSize(new java.awt.Dimension(100, 40));
        jb_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_cancelarActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Fornecedor"));
        jPanel1.setName("jPanel1"); // NOI18N

        jftf_telefone.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jftf_telefone.setName("jftf_telefone"); // NOI18N
        jftf_telefone.setPreferredSize(new java.awt.Dimension(14, 24));
        jftf_telefone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jftf_telefoneKeyPressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jLabel7.setText("CNPJ");
        jLabel7.setName("jLabel7"); // NOI18N

        jtf_nome_fantasia.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jtf_nome_fantasia.setName("jtf_nome_fantasia"); // NOI18N
        jtf_nome_fantasia.setPreferredSize(new java.awt.Dimension(300, 24));
        jtf_nome_fantasia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtf_nome_fantasiaKeyPressed(evt);
            }
        });

        jtf_cidade.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jtf_cidade.setName("jtf_cidade"); // NOI18N
        jtf_cidade.setPreferredSize(new java.awt.Dimension(14, 24));
        jtf_cidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtf_cidadeKeyPressed(evt);
            }
        });

        jtf_estado.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jtf_estado.setName("jtf_estado"); // NOI18N
        jtf_estado.setPreferredSize(new java.awt.Dimension(14, 24));
        jtf_estado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtf_estadoKeyPressed(evt);
            }
        });

        jftf_tel_vendedor.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jftf_tel_vendedor.setName("jftf_tel_vendedor"); // NOI18N
        jftf_tel_vendedor.setPreferredSize(new java.awt.Dimension(14, 24));
        jftf_tel_vendedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jftf_tel_vendedorKeyPressed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jLabel15.setText("Telefone do Vendedor");
        jLabel15.setName("jLabel15"); // NOI18N

        jtf_endereco.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jtf_endereco.setName("jtf_endereco"); // NOI18N
        jtf_endereco.setPreferredSize(new java.awt.Dimension(150, 24));
        jtf_endereco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtf_enderecoKeyPressed(evt);
            }
        });

        jtf_nome_vendedor.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jtf_nome_vendedor.setName("jtf_nome_vendedor"); // NOI18N
        jtf_nome_vendedor.setPreferredSize(new java.awt.Dimension(14, 24));
        jtf_nome_vendedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtf_nome_vendedorKeyPressed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jLabel10.setText("Estado*");
        jLabel10.setName("jLabel10"); // NOI18N

        jLabel9.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jLabel9.setText("Fax");
        jLabel9.setName("jLabel9"); // NOI18N

        jLabel11.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jLabel11.setText("Cidade*");
        jLabel11.setName("jLabel11"); // NOI18N

        jLabel14.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jLabel14.setText("Nome Vendedor*");
        jLabel14.setName("jLabel14"); // NOI18N

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jLabel6.setText("Endereço*");
        jLabel6.setName("jLabel6"); // NOI18N

        jftf_cnpj.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jftf_cnpj.setName("jftf_cnpj"); // NOI18N
        jftf_cnpj.setPreferredSize(new java.awt.Dimension(14, 24));
        jftf_cnpj.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jftf_cnpjFocusLost(evt);
            }
        });
        jftf_cnpj.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jftf_cnpjKeyPressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jLabel3.setText("Código");
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jLabel5.setText("Nome Fantasia*");
        jLabel5.setName("jLabel5"); // NOI18N

        jftf_fax.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jftf_fax.setName("jftf_fax"); // NOI18N
        jftf_fax.setPreferredSize(new java.awt.Dimension(14, 24));
        jftf_fax.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jftf_faxKeyPressed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jLabel8.setText("Telefone*");
        jLabel8.setName("jLabel8"); // NOI18N

        jtf_codigo_fornecedor.setEditable(false);
        jtf_codigo_fornecedor.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jtf_codigo_fornecedor.setName("jtf_codigo_fornecedor"); // NOI18N

        jLabel17.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jLabel17.setText("Bairro");
        jLabel17.setName("jLabel17"); // NOI18N

        jtf_bairro.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jtf_bairro.setName("jtf_bairro"); // NOI18N
        jtf_bairro.setPreferredSize(new java.awt.Dimension(100, 24));
        jtf_bairro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtf_bairroKeyPressed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jLabel18.setText("Complemento");
        jLabel18.setName("jLabel18"); // NOI18N

        jtf_complemento.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jtf_complemento.setName("jtf_complemento"); // NOI18N
        jtf_complemento.setPreferredSize(new java.awt.Dimension(150, 24));
        jtf_complemento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtf_complementoKeyPressed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jLabel16.setText("Razão Social *");
        jLabel16.setName("jLabel16"); // NOI18N

        jtf_razao_social.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jtf_razao_social.setName("jtf_razao_social"); // NOI18N
        jtf_razao_social.setPreferredSize(new java.awt.Dimension(300, 24));
        jtf_razao_social.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtf_razao_socialKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jtf_endereco, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_bairro, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jtf_complemento, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jtf_cidade, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jtf_estado, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jftf_cnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jftf_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jftf_fax, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel3)
                    .addComponent(jtf_codigo_fornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jtf_nome_vendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jftf_tel_vendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jtf_nome_fantasia, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jtf_razao_social, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel3)
                .addGap(0, 0, 0)
                .addComponent(jtf_codigo_fornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(0, 0, 0)
                                .addComponent(jtf_nome_fantasia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(0, 0, 0)
                                .addComponent(jtf_razao_social, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, 0)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(0, 0, 0)
                                .addComponent(jtf_endereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel18))
                                .addGap(0, 0, 0)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtf_bairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtf_complemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, 0)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11))
                                .addGap(0, 0, 0)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jtf_estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtf_cidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(0, 0, 0)
                                .addComponent(jftf_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(0, 0, 0)
                                .addComponent(jftf_fax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(0, 0, 0)
                        .addComponent(jftf_cnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtf_nome_vendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jftf_tel_vendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(412, 412, 412)
                        .addComponent(jb_salvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jb_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jb_salvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jb_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        setSize(new java.awt.Dimension(653, 331));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jb_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_cancelarActionPerformed
        retornaJanelaPai();
        // TODO add your handling code here:
}//GEN-LAST:event_jb_cancelarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        jtf_nome_fantasia.requestFocus();
        
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        janelapai.setStatusTela(true);
        setVisible(false);
    }//GEN-LAST:event_formWindowClosed

    private void jtf_razao_socialKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_razao_socialKeyPressed
        acionarAtalho(evt);
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtf_endereco.requestFocus();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_razao_socialKeyPressed

    private void jtf_nome_fantasiaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_nome_fantasiaKeyPressed
        acionarAtalho(evt);
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtf_razao_social.requestFocus();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_nome_fantasiaKeyPressed

    private void jtf_enderecoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_enderecoKeyPressed
        acionarAtalho(evt);
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtf_bairro.requestFocus();
        }
    }//GEN-LAST:event_jtf_enderecoKeyPressed

    private void jtf_estadoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_estadoKeyPressed
        acionarAtalho(evt);
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jftf_cnpj.requestFocus();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_estadoKeyPressed

    private void jtf_cidadeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_cidadeKeyPressed
        acionarAtalho(evt);
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtf_estado.requestFocus();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_cidadeKeyPressed

    private void jftf_cnpjKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jftf_cnpjKeyPressed
        acionarAtalho(evt);
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jftf_telefone.requestFocus();
        }
    }//GEN-LAST:event_jftf_cnpjKeyPressed

    private void jftf_cnpjFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jftf_cnpjFocusLost
//        jftf_cnpj.setFocusLostBehavior(JFormattedTextField.COMMIT);
        //JOptionPane.showMessageDialog(null,"Inválido cnpj");
        try {
            if (!(validaCnpj(jftf_cnpj.getText().trim()))) {
                //  JOptionPane.showMessageDialog(null,"Inválido");
                jftf_cnpj.setForeground(Color.red);
            } else {
                jftf_cnpj.setForeground(Color.BLACK);
            }            
        } catch (Exception e) {
            jftf_cnpj.setForeground(Color.red);
        }
    }//GEN-LAST:event_jftf_cnpjFocusLost

    private void jftf_faxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jftf_faxKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtf_nome_vendedor.requestFocus();
        }
    }//GEN-LAST:event_jftf_faxKeyPressed

    private void jftf_telefoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jftf_telefoneKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jftf_fax.requestFocus();
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jftf_telefoneKeyPressed

    private void jtf_nome_vendedorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_nome_vendedorKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jftf_tel_vendedor.requestFocus();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_nome_vendedorKeyPressed

    private void jftf_tel_vendedorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jftf_tel_vendedorKeyPressed
        acionarAtalho(evt);
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jb_salvar.requestFocus();
        }
    }//GEN-LAST:event_jftf_tel_vendedorKeyPressed

    private void jtf_bairroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_bairroKeyPressed
        acionarAtalho(evt);
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtf_complemento.requestFocus();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_bairroKeyPressed

    private void jtf_complementoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_complementoKeyPressed
        acionarAtalho(evt);
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtf_cidade.requestFocus();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_complementoKeyPressed

    private void jb_salvarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jb_salvarKeyPressed
        acionarAtalho(evt);
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            cadastraFornecedor();            
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_salvarKeyPressed

    private void jb_salvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_salvarMouseClicked
        
        if(evt.getClickCount() == 1){
            cadastraFornecedor();            
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_salvarMouseClicked

    private void jb_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_salvarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_salvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new CadastraAlteraFornecedor().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jb_cancelar;
    private javax.swing.JButton jb_salvar;
    private javax.swing.JFormattedTextField jftf_cnpj;
    private javax.swing.JFormattedTextField jftf_fax;
    private javax.swing.JFormattedTextField jftf_tel_vendedor;
    private javax.swing.JFormattedTextField jftf_telefone;
    public static javax.swing.JTextField jtf_bairro;
    private javax.swing.JTextField jtf_cidade;
    private javax.swing.JTextField jtf_codigo_fornecedor;
    public static javax.swing.JTextField jtf_complemento;
    private javax.swing.JTextField jtf_endereco;
    private javax.swing.JTextField jtf_estado;
    private javax.swing.JTextField jtf_nome_fantasia;
    private javax.swing.JTextField jtf_nome_vendedor;
    private javax.swing.JTextField jtf_razao_social;
    // End of variables declaration//GEN-END:variables

    private void cadastraFornecedor() {

        if (verificarCampos()) {
            pool = new Pool();
            fornecedorDAO = new FornecedorDAO(pool);
            fornecedor = new Fornecedor();
            fornecedor.setRazao_social(jtf_razao_social.getText().trim());
            fornecedor.setNome_fantasia(jtf_nome_fantasia.getText().trim());
            fornecedor.setEndereço(jtf_endereco.getText().trim());
            fornecedor.setBairro(jtf_bairro.getText().trim());
            fornecedor.setComplemento(jtf_complemento.getText().trim());
            fornecedor.setCidade(jtf_cidade.getText().trim());
            fornecedor.setEstado(jtf_estado.getText().trim());
            if (jftf_cnpj.getForeground().equals(Color.BLACK)) {
                fornecedor.setCnpj(jftf_cnpj.getText().trim());
            }
            fornecedor.setTelefone(jftf_telefone.getText().trim());
            fornecedor.setFax(jftf_fax.getText().trim());
            fornecedor.setNome_vendedor(jtf_nome_vendedor.getText().trim());
            fornecedor.setTel_vendedor(jftf_tel_vendedor.getText().trim());

            if (jtf_codigo_fornecedor.getText().equals("")) {
                LogInfo logInfo = new LogInfo();
                logInfo.setDescricao("Novo Fornecedor: "+jtf_nome_fantasia.getText());
                logInfo.setUsuario(acesso.getUsuario());
                pool = new Pool();
                LogInfoDAO logInfoDAO = new LogInfoDAO(pool);
                logInfoDAO.salvar(logInfo);

                
                fornecedor = fornecedorDAO.salvar(fornecedor);
                jtf_codigo_fornecedor.setText(fornecedor.getCodigo_fornecedor().toString());
                this.setTitle("Alterando Fornecedor");
                JOptionPane.showMessageDialog(null, "Cadastrado com Sucesso!");
            } else {
                LogInfo logInfo = new LogInfo();
                logInfo.setDescricao("Alterar Fornecedor -> "+fornecedor.getNome_fantasia()+ " -> " + jtf_nome_fantasia.getText());
                logInfo.setUsuario(acesso.getUsuario());
                pool = new Pool();
                LogInfoDAO logInfoDAO = new LogInfoDAO(pool);
                logInfoDAO.salvar(logInfo);
                    
                fornecedor.setCodigo_fornecedor(Integer.parseInt(jtf_codigo_fornecedor.getText()));
                fornecedorDAO.atualizar(fornecedor);
                JOptionPane.showMessageDialog(null, "Alterado com Sucesso!");
            }
        }
    }
    List<Fornecedor> fornecedores;

    public void verificaCadastro() {
        pool = new Pool();
        fornecedorDAO = new FornecedorDAO(pool);
        fornecedores = fornecedorDAO.getFornecedorNomeFantasia(jtf_nome_fantasia.getText().trim());
        validaCadastro(fornecedores);
    }

    public void validaCadastro(List<Fornecedor> fornecedores) {//verifica cadastro existente que retornou de uma lista

        if (fornecedores.size() == 0) {
            cadastraFornecedor();
        } else {
            JOptionPane.showMessageDialog(null, "Fornecedor existente");
            jtf_razao_social.requestFocus();
        }
    }

    public boolean verificarCampos() {

        String msgERRO = "Preencha os campos obrigatórios:\n";

        if (jtf_razao_social.getText().equals("")) {
            msgERRO = msgERRO + " *Razão Social\n";
        }

        if (jtf_nome_fantasia.getText().equals("")) {
            msgERRO = msgERRO + " *Nome Fantasia\n";
        }

        if (jtf_endereco.getText().equals("")) {
            msgERRO = msgERRO + " *Endereço\n";
        }

        if (jftf_telefone.getText().equals("(  )    -    ")) {
            msgERRO = msgERRO + " *Telefone\n";
        }

        if (jtf_cidade.getText().equals("")) {
            msgERRO = msgERRO + " *Cidade\n";
        }

        if (jtf_estado.getText().equals("")) {
            msgERRO = msgERRO + " *Estado\n";
        }

        if (jtf_nome_vendedor.getText().equals("")) {
            msgERRO = msgERRO + " *Nome do Vendedor\n";
        }
        
        try {
            if (!(validaCnpj(jftf_cnpj.getText().trim()))) {                
                jftf_cnpj.setForeground(Color.red);
            } else {
                jftf_cnpj.setForeground(Color.BLACK);
            }            
        } catch (Exception e) {
            jftf_cnpj.setForeground(Color.red);
        }

        if (!msgERRO.equals("Preencha os campos obrigatórios:\n")) {
            JOptionPane.showMessageDialog(this, msgERRO);
            jtf_nome_fantasia.requestFocus();
            return false;
        } else {
            return true;
        }
    }

    public boolean validaCNPJ(boolean validado) {
        ValidaCnpj cnpj = new ValidaCnpj();
        validado = cnpj.validaCnpj(jftf_cnpj.getText());
        if (validado) {
            return true;
        } //validacnpj
        // faz alguma coisa
        else {
            JOptionPane.showMessageDialog(null, "CNPJ inválido");
            jftf_cnpj.requestFocus();
            return false;
        }
    }

    public static boolean validaCnpj(String str_cnpj) {
        
        if (!str_cnpj.substring(0, 1).equals("")) {
            //  try{
            str_cnpj = str_cnpj.replace('.', ' ');
            str_cnpj = str_cnpj.replace('/', ' ');
            str_cnpj = str_cnpj.replace('-', ' ');
            str_cnpj = str_cnpj.replaceAll(" ", "");
            int soma = 0, aux, dig;
            String cnpj_calc = str_cnpj.substring(0, 12);

            if (str_cnpj.length() != 14) {
                return false;
            }
            char[] chr_cnpj = str_cnpj.toCharArray();
            /* Primeira parte */
            for (int i = 0; i < 4; i++) {
                if (chr_cnpj[i] - 48 >= 0 && chr_cnpj[i] - 48 <= 9) {
                    soma += (chr_cnpj[i] - 48) * (6 - (i + 1));
                }
            }
            for (int i = 0; i < 8; i++) {
                if (chr_cnpj[i + 4] - 48 >= 0 && chr_cnpj[i + 4] - 48 <= 9) {
                    soma += (chr_cnpj[i + 4] - 48) * (10 - (i + 1));
                }
            }
            dig = 11 - (soma % 11);
            cnpj_calc += (dig == 10 || dig == 11)
                    ? "0" : Integer.toString(dig);
            /* Segunda parte */
            soma = 0;
            for (int i = 0; i < 5; i++) {
                if (chr_cnpj[i] - 48 >= 0 && chr_cnpj[i] - 48 <= 9) {
                    soma += (chr_cnpj[i] - 48) * (7 - (i + 1));
                }
            }
            for (int i = 0; i < 8; i++) {
                if (chr_cnpj[i + 5] - 48 >= 0 && chr_cnpj[i + 5] - 48 <= 9) {
                    soma += (chr_cnpj[i + 5] - 48) * (10 - (i + 1));
                }
            }
            dig = 11 - (soma % 11);
            cnpj_calc += (dig == 10 || dig == 11)
                    ? "0" : Integer.toString(dig);
            return str_cnpj.equals(cnpj_calc);
            //}catch (Exception e){
            //  System.err.println("Erro !"+e);
            //return false;
            //}
        } else {
            return false;
        }

    }

    public void acionarAtalho(java.awt.event.KeyEvent evt) {
        if (evt.getKeyCode() == KeyEvent.VK_F10) {
            cadastraFornecedor();
        }
        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            retornaJanelaPai();
        }
    }

    public void retornaJanelaPai() {
        setVisible(false);
        if (janelapai != null) {
            janelapai.setStatusTela(true);
            janelapai.getFornecedores();
            janelapai.cadastra_altera_fornecedor = null;
        } else if(janelapai2 != null){
            janelapai2.setStatusTela(true);            
            janelapai2.cadastraAlteraFornecedor = null;
        }
    }
}
