package br.com.locadora.view;

import br.com.locadora.conexao.InterfacePool;
import br.com.locadora.conexao.Pool;
import br.com.locadora.controller.SiscomController;
import br.com.locadora.model.bean.AcessoUsuario;
import br.com.locadora.model.bean.Cliente;
import br.com.locadora.model.bean.Copia;
import br.com.locadora.model.bean.Devolucao;
import br.com.locadora.model.bean.ItemLancamento;
import br.com.locadora.model.bean.ItemLocacao;
import br.com.locadora.model.bean.Lancamento;
import br.com.locadora.model.bean.Locacao;
import br.com.locadora.model.bean.TipoServico;
import br.com.locadora.model.bean.Usuario;
import br.com.locadora.model.bean.Venda;
import br.com.locadora.model.dao.ClienteDAO;
import br.com.locadora.model.dao.CopiaDAO;
import br.com.locadora.model.dao.DevolucaoDAO;
import br.com.locadora.model.dao.LancamentoDAO;
import br.com.locadora.model.dao.LocacaoDAO;
import br.com.locadora.model.dao.UsuarioDAO;
import br.com.locadora.util.ArquivoConfiguracao;
import br.com.locadora.util.Printer;
import br.com.locadora.util.LimitadorTexto;
import br.com.locadora.util.Moeda;
import br.com.locadora.util.TemaInterface;
import br.com.locadora.util.UnaccentedDocument;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.io.File;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ALENCAR
 */
public final class EntradaCaixaDevolucao extends javax.swing.JFrame {

    public AtendimentoDevolucao janelapaiDevolucao;
    public InterfacePool pool;
    public SiscomController controller;
    public String action;
    public static List<ItemLocacao> itens;
    public Moeda moeda;
    public LancamentoDAO lancamentoDAO;
    public Lancamento lancamento;
    public Cliente cliente;

    /**
     * Creates new form ProdutoCadastroGUI
     */
    public EntradaCaixaDevolucao() {
        initComponents();
        TemaInterface.getInterface(this);
        janelapaiDevolucao = null;
    }

    //public ProdutoConsultarGUI janelapaim;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tfa_similar = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jtf_login = new javax.swing.JTextField();
        jpf_senha = new javax.swing.JPasswordField();
        jb_logar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jtf_total_relocacao = new javax.swing.JTextField(new LimitadorTexto(80), "",10);
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtf_troco = new javax.swing.JTextField(new LimitadorTexto(80), "",10);
        jtf_debito_atual = new javax.swing.JTextField(new LimitadorTexto(80), "",10);
        jl_saldo_debito_atual = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtf_total_a_pagar = new javax.swing.JTextField(new LimitadorTexto(80), "",10);
        jLabel6 = new javax.swing.JLabel();
        jtf_valor_pago = new javax.swing.JTextField(new LimitadorTexto(80), "",10);
        jtf_desconto_entrega_antecipada = new javax.swing.JTextField(new LimitadorTexto(80), "",10);
        jLabel8 = new javax.swing.JLabel();
        jl_saldo = new javax.swing.JLabel();
        jtf_saldo = new javax.swing.JTextField(new LimitadorTexto(80), "",10);
        jLabel5 = new javax.swing.JLabel();
        jtf_desconto = new javax.swing.JTextField(new LimitadorTexto(80), "",10);
        jPanel3 = new javax.swing.JPanel();
        jb_salvar = new javax.swing.JButton();
        jb_imprimir = new javax.swing.JButton();
        jb_sair = new javax.swing.JButton();

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        tfa_similar.setColumns(20);
        tfa_similar.setRows(5);
        tfa_similar.setName("tfa_similar"); // NOI18N
        jScrollPane1.setViewportView(tfa_similar);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Caixa - Atendimento Devolução");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Verificar Permissão"));
        jPanel1.setName("jPanel1"); // NOI18N

        jtf_login.setEditable(false);
        jtf_login.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jtf_login.setName("jtf_login"); // NOI18N
        jtf_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_loginActionPerformed(evt);
            }
        });
        jtf_login.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtf_loginKeyPressed(evt);
            }
        });

        jpf_senha.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jpf_senha.setName("jpf_senha"); // NOI18N
        jpf_senha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jpf_senhaKeyPressed(evt);
            }
        });

        jb_logar.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        jb_logar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/locadora/image/login.png"))); // NOI18N
        jb_logar.setText("Entrar");
        jb_logar.setName("jb_logar"); // NOI18N
        jb_logar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_logarActionPerformed(evt);
            }
        });
        jb_logar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jb_logarKeyPressed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jLabel9.setText("Senha:");
        jLabel9.setName("jLabel9"); // NOI18N

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jLabel4.setText("Login:");
        jLabel4.setName("jLabel4"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jtf_login, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jpf_senha, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jb_logar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel9))
                        .addGap(0, 0, 0)
                        .addComponent(jtf_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jb_logar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jpf_senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, 0))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jb_logar, jtf_login});

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Caixa"));
        jPanel2.setName("jPanel2"); // NOI18N

        jtf_total_relocacao.setDocument(new UnaccentedDocument());
        jtf_total_relocacao.setEditable(false);
        jtf_total_relocacao.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jtf_total_relocacao.setForeground(new java.awt.Color(204, 0, 0));
        jtf_total_relocacao.setText("R$ 0,00");
        jtf_total_relocacao.setName("jtf_total_relocacao");
        jtf_total_relocacao.setPreferredSize(new java.awt.Dimension(120, 29));
        jtf_total_relocacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_total_relocacaoActionPerformed(evt);
            }
        });
        jtf_total_relocacao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtf_total_relocacaoFocusGained(evt);
            }
        });
        jtf_total_relocacao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtf_total_relocacaoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtf_total_relocacaoKeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Total Relocação (-)");
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Troco (+)");
        jLabel7.setName("jLabel7"); // NOI18N

        jtf_total_relocacao.setDocument(new UnaccentedDocument());
        jtf_troco.setEditable(false);
        jtf_troco.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jtf_troco.setText("R$ 0,00");
        jtf_troco.setName("jtf_troco"); // NOI18N
        jtf_troco.setPreferredSize(new java.awt.Dimension(120, 29));
        jtf_troco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_trocoActionPerformed(evt);
            }
        });
        jtf_troco.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtf_trocoFocusGained(evt);
            }
        });
        jtf_troco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtf_trocoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtf_trocoKeyReleased(evt);
            }
        });

        jtf_total_relocacao.setDocument(new UnaccentedDocument());
        jtf_debito_atual.setEditable(false);
        jtf_debito_atual.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jtf_debito_atual.setForeground(new java.awt.Color(204, 0, 0));
        jtf_debito_atual.setText("R$ 0,00");
        jtf_debito_atual.setName("jtf_debito_atual"); // NOI18N
        jtf_debito_atual.setPreferredSize(new java.awt.Dimension(120, 29));
        jtf_debito_atual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_debito_atualActionPerformed(evt);
            }
        });
        jtf_debito_atual.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtf_debito_atualFocusGained(evt);
            }
        });
        jtf_debito_atual.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtf_debito_atualKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtf_debito_atualKeyReleased(evt);
            }
        });

        jl_saldo_debito_atual.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jl_saldo_debito_atual.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jl_saldo_debito_atual.setText("Débito Atual (-)");
        jl_saldo_debito_atual.setName("jl_saldo_debito_atual"); // NOI18N

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Total Á Pagar (=)");
        jLabel3.setName("jLabel3"); // NOI18N

        jtf_total_relocacao.setDocument(new UnaccentedDocument());
        jtf_total_a_pagar.setEditable(false);
        jtf_total_a_pagar.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jtf_total_a_pagar.setForeground(new java.awt.Color(204, 0, 0));
        jtf_total_a_pagar.setText("R$ 0,00");
        jtf_total_a_pagar.setName("jtf_total_a_pagar"); // NOI18N
        jtf_total_a_pagar.setPreferredSize(new java.awt.Dimension(120, 29));
        jtf_total_a_pagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_total_a_pagarActionPerformed(evt);
            }
        });
        jtf_total_a_pagar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtf_total_a_pagarFocusGained(evt);
            }
        });
        jtf_total_a_pagar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtf_total_a_pagarKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtf_total_a_pagarKeyReleased(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Valor Pago (+)");
        jLabel6.setName("jLabel6"); // NOI18N

        jtf_total_relocacao.setDocument(new UnaccentedDocument());
        jtf_valor_pago.setEditable(false);
        jtf_valor_pago.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jtf_valor_pago.setText("R$ 0,00");
        jtf_valor_pago.setEnabled(false);
        jtf_valor_pago.setName("jtf_valor_pago"); // NOI18N
        jtf_valor_pago.setPreferredSize(new java.awt.Dimension(120, 29));
        jtf_valor_pago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_valor_pagoActionPerformed(evt);
            }
        });
        jtf_valor_pago.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtf_valor_pagoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtf_valor_pagoFocusLost(evt);
            }
        });
        jtf_valor_pago.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtf_valor_pagoKeyPressed(evt);
            }
        });

        jtf_total_relocacao.setDocument(new UnaccentedDocument());
        jtf_desconto_entrega_antecipada.setEditable(false);
        jtf_desconto_entrega_antecipada.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jtf_desconto_entrega_antecipada.setText("R$ 0,00");
        jtf_desconto_entrega_antecipada.setEnabled(false);
        jtf_desconto_entrega_antecipada.setName("jtf_desconto_entrega_antecipada"); // NOI18N
        jtf_desconto_entrega_antecipada.setPreferredSize(new java.awt.Dimension(120, 29));
        jtf_desconto_entrega_antecipada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_desconto_entrega_antecipadaActionPerformed(evt);
            }
        });
        jtf_desconto_entrega_antecipada.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtf_desconto_entrega_antecipadaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtf_desconto_entrega_antecipadaFocusLost(evt);
            }
        });
        jtf_desconto_entrega_antecipada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtf_desconto_entrega_antecipadaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtf_desconto_entrega_antecipadaKeyReleased(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Desconto Entrega Antecipada (+)");
        jLabel8.setName("jLabel8"); // NOI18N

        jl_saldo.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jl_saldo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jl_saldo.setText("Saldo (+)");
        jl_saldo.setName("jl_saldo"); // NOI18N

        jtf_total_relocacao.setDocument(new UnaccentedDocument());
        jtf_saldo.setEditable(false);
        jtf_saldo.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jtf_saldo.setText("R$ 0,00");
        jtf_saldo.setName("jtf_saldo"); // NOI18N
        jtf_saldo.setPreferredSize(new java.awt.Dimension(120, 29));
        jtf_saldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_saldoActionPerformed(evt);
            }
        });
        jtf_saldo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtf_saldoFocusGained(evt);
            }
        });
        jtf_saldo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtf_saldoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtf_saldoKeyReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Valor Desconto (+)");
        jLabel5.setName("jLabel5"); // NOI18N

        jtf_total_relocacao.setDocument(new UnaccentedDocument());
        jtf_desconto.setEditable(false);
        jtf_desconto.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jtf_desconto.setText("R$ 0,00");
        jtf_desconto.setEnabled(false);
        jtf_desconto.setName("jtf_desconto"); // NOI18N
        jtf_desconto.setPreferredSize(new java.awt.Dimension(120, 29));
        jtf_desconto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_descontoActionPerformed(evt);
            }
        });
        jtf_desconto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtf_descontoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtf_descontoFocusLost(evt);
            }
        });
        jtf_desconto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtf_descontoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtf_descontoKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jl_saldo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtf_saldo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtf_total_relocacao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtf_desconto_entrega_antecipada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtf_total_a_pagar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtf_desconto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jl_saldo_debito_atual, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtf_debito_atual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_valor_pago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_troco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(10, 10, 10))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jtf_debito_atual, jtf_desconto, jtf_desconto_entrega_antecipada, jtf_saldo, jtf_total_a_pagar, jtf_total_relocacao, jtf_troco, jtf_valor_pago});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_saldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_saldo))
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_total_relocacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_desconto_entrega_antecipada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_desconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_total_a_pagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_valor_pago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_troco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_debito_atual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_saldo_debito_atual))
                .addGap(10, 10, 10))
        );

        jPanel3.setName("jPanel3"); // NOI18N

        jb_salvar.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jb_salvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/locadora/image/save.png"))); // NOI18N
        jb_salvar.setText("Salvar");
        jb_salvar.setEnabled(false);
        jb_salvar.setName("jb_salvar"); // NOI18N
        jb_salvar.setPreferredSize(new java.awt.Dimension(100, 40));
        jb_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_salvarActionPerformed(evt);
            }
        });
        jb_salvar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jb_salvarKeyPressed(evt);
            }
        });

        jb_imprimir.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jb_imprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/locadora/image/printer.png"))); // NOI18N
        jb_imprimir.setText("Imprimir");
        jb_imprimir.setEnabled(false);
        jb_imprimir.setMaximumSize(new java.awt.Dimension(101, 33));
        jb_imprimir.setName("jb_imprimir"); // NOI18N
        jb_imprimir.setPreferredSize(new java.awt.Dimension(100, 40));
        jb_imprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_imprimirActionPerformed(evt);
            }
        });
        jb_imprimir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jb_imprimirKeyPressed(evt);
            }
        });

        jb_sair.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jb_sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/locadora/image/sair.png"))); // NOI18N
        jb_sair.setText("Sair");
        jb_sair.setMaximumSize(new java.awt.Dimension(101, 33));
        jb_sair.setName("jb_sair"); // NOI18N
        jb_sair.setPreferredSize(new java.awt.Dimension(100, 40));
        jb_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_sairActionPerformed(evt);
            }
        });
        jb_sair.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jb_sairKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jb_salvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jb_imprimir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jb_sair, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jb_salvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jb_imprimir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jb_sair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        jpf_senha.requestFocus();
        if (janelapaiDevolucao != null) {
            recalcularValores();
        }
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        retornaJanelaPai();
    }//GEN-LAST:event_formWindowClosed

    private void jtf_total_relocacaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_total_relocacaoKeyPressed
        acionarAtalho(evt);
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_total_relocacaoKeyPressed
    private void jtf_total_relocacaoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtf_total_relocacaoFocusGained

        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_total_relocacaoFocusGained

    private void jtf_total_relocacaoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_total_relocacaoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_total_relocacaoKeyReleased

    private void jtf_total_relocacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_total_relocacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_total_relocacaoActionPerformed

    private void jtf_descontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_descontoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_descontoActionPerformed

    private void jtf_descontoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtf_descontoFocusGained
        jtf_desconto.selectAll();
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_descontoFocusGained

    private void jtf_descontoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_descontoKeyPressed
        acionarAtalho(evt);
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtf_valor_pago.requestFocus();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_descontoKeyPressed

    private void jtf_descontoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_descontoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_descontoKeyReleased

    private void jtf_valor_pagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_valor_pagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_valor_pagoActionPerformed

    private void jtf_valor_pagoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtf_valor_pagoFocusGained
        jtf_valor_pago.selectAll();
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_valor_pagoFocusGained

    private void jtf_valor_pagoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_valor_pagoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            System.out.println("Campo jtf_desconto == " + jtf_desconto.isEditable());
            jb_salvar.requestFocus();
        }
        acionarAtalho(evt);
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_valor_pagoKeyPressed

    private void jtf_trocoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_trocoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_trocoActionPerformed

    private void jtf_trocoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtf_trocoFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_trocoFocusGained

    private void jtf_trocoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_trocoKeyPressed
        acionarAtalho(evt);
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_trocoKeyPressed

    private void jtf_trocoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_trocoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_trocoKeyReleased

    private void jtf_debito_atualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_debito_atualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_debito_atualActionPerformed

    private void jtf_debito_atualFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtf_debito_atualFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_debito_atualFocusGained

    private void jtf_debito_atualKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_debito_atualKeyPressed
        acionarAtalho(evt);
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_debito_atualKeyPressed

    private void jtf_debito_atualKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_debito_atualKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_debito_atualKeyReleased

    private void jtf_valor_pagoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtf_valor_pagoFocusLost
        recalcularValores();
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_valor_pagoFocusLost

    private void jtf_loginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_loginKeyPressed
        acionarAtalho(evt);
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_loginKeyPressed

    private void jpf_senhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jpf_senhaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jb_logar.doClick();
        }
        acionarAtalho(evt);
    }//GEN-LAST:event_jpf_senhaKeyPressed

    private void jb_logarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_logarActionPerformed
        entrar();
    }//GEN-LAST:event_jb_logarActionPerformed

    private void jtf_descontoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtf_descontoFocusLost
        recalcularValores();
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_descontoFocusLost

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        acionarAtalho(evt);
        // TODO add your handling code here:
    }//GEN-LAST:event_formKeyPressed

    private void jb_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_sairActionPerformed
        retornaJanelaPai();
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_sairActionPerformed

    private void jtf_saldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_saldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_saldoActionPerformed

    private void jtf_saldoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtf_saldoFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_saldoFocusGained

    private void jtf_saldoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_saldoKeyPressed
        acionarAtalho(evt);
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_saldoKeyPressed

    private void jtf_saldoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_saldoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_saldoKeyReleased

    private void jtf_total_a_pagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_total_a_pagarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_total_a_pagarActionPerformed

    private void jtf_total_a_pagarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtf_total_a_pagarFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_total_a_pagarFocusGained

    private void jtf_total_a_pagarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_total_a_pagarKeyPressed
        acionarAtalho(evt);
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_total_a_pagarKeyPressed

    private void jtf_total_a_pagarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_total_a_pagarKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_total_a_pagarKeyReleased

    private void jb_salvarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jb_salvarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jb_salvar.doClick();
        }
        acionarAtalho(evt);
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_salvarKeyPressed

    private void jb_imprimirKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jb_imprimirKeyPressed
        acionarAtalho(evt);
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jb_imprimir.doClick();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_imprimirKeyPressed

    private void jb_sairKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jb_sairKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jb_sair.doClick();
        }
        acionarAtalho(evt);
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_sairKeyPressed

    private void jtf_desconto_entrega_antecipadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_desconto_entrega_antecipadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_desconto_entrega_antecipadaActionPerformed

    private void jtf_desconto_entrega_antecipadaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtf_desconto_entrega_antecipadaFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_desconto_entrega_antecipadaFocusGained

    private void jtf_desconto_entrega_antecipadaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtf_desconto_entrega_antecipadaFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_desconto_entrega_antecipadaFocusLost

    private void jtf_desconto_entrega_antecipadaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_desconto_entrega_antecipadaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_desconto_entrega_antecipadaKeyPressed

    private void jtf_desconto_entrega_antecipadaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_desconto_entrega_antecipadaKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_desconto_entrega_antecipadaKeyReleased

    private void jtf_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_loginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_loginActionPerformed

    private void jb_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_salvarActionPerformed

        finalizarCaixa();

        // TODO add your handling code here:
    }//GEN-LAST:event_jb_salvarActionPerformed

    private void jb_logarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jb_logarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jb_logar.doClick();
        }
        acionarAtalho(evt);
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_logarKeyPressed

    private void jb_imprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_imprimirActionPerformed
        imprimir();
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_imprimirActionPerformed

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new EntradaCaixaDevolucao().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jb_imprimir;
    private javax.swing.JButton jb_logar;
    private javax.swing.JButton jb_sair;
    private javax.swing.JButton jb_salvar;
    private javax.swing.JLabel jl_saldo;
    private javax.swing.JLabel jl_saldo_debito_atual;
    private javax.swing.JPasswordField jpf_senha;
    public static javax.swing.JTextField jtf_debito_atual;
    public static javax.swing.JTextField jtf_desconto;
    public static javax.swing.JTextField jtf_desconto_entrega_antecipada;
    private javax.swing.JTextField jtf_login;
    public static javax.swing.JTextField jtf_saldo;
    public static javax.swing.JTextField jtf_total_a_pagar;
    public static javax.swing.JTextField jtf_total_relocacao;
    public static javax.swing.JTextField jtf_troco;
    public static javax.swing.JTextField jtf_valor_pago;
    private javax.swing.JTextArea tfa_similar;
    // End of variables declaration//GEN-END:variables

    public boolean verificarTempoCadastro() {
        DateFormat df = new SimpleDateFormat("dd/MM/yyyy");

        pool = new Pool();
        ClienteDAO clienteDAO = new ClienteDAO(pool);
        cliente = clienteDAO.getCliente_codigo(janelapaiDevolucao.dependente.getCliente().getCodigo_cliente()).get(0);

        if (cliente != null) {

            Calendar data_inicial = Calendar.getInstance();
            data_inicial.setTime(cliente.getData_cadastro());
            data_inicial.set(Calendar.HOUR_OF_DAY, 0);
            data_inicial.set(Calendar.MINUTE, 0);
            data_inicial.set(Calendar.SECOND, 0);
            data_inicial.set(Calendar.MILLISECOND, 0);
            data_inicial.getTime();

            Calendar data_final = Calendar.getInstance();
            data_final.set(Calendar.HOUR_OF_DAY, 0);
            data_final.set(Calendar.MINUTE, 0);
            data_final.set(Calendar.SECOND, 0);
            data_final.set(Calendar.MILLISECOND, 0);
            data_final.getTime();

            long intervalo = data_final.getTimeInMillis() - data_inicial.getTimeInMillis();
            int duracaoCadastro = (int) (intervalo / (1000 * 60 * 60 * 24 * 30)); // resultado em meses 
            System.out.println("Calculo de dias em Cadastro:" + duracaoCadastro);

            ConfiguraSistema configuraSistema = new ConfiguraSistema();
            int tempo_inadiplente = Integer.parseInt(configuraSistema.jtf_a_prazo_cadastro_mes.getText());

            if (duracaoCadastro < tempo_inadiplente) {
                return false;
            } else {
                return true;
            }
        } else {
            return false;
        }
    }

    public void setStatusTela(boolean status) {
        if (status) {
            this.setVisible(status);
        }
        this.setEnabled(status);
    }

    private void entrar() {

        if (validaLogin()) {
            if (verificaLogin()) {
                jtf_login.setText(acesso.getUsuario().getLogin());
                jb_salvar.setEnabled(true);
                if (acesso.getEscrever() == true) {
                    jtf_valor_pago.setEditable(true);
                    jtf_valor_pago.setEnabled(true);
                    jtf_desconto.setEditable(true);
                    jtf_desconto.setEnabled(true);
                    jtf_valor_pago.requestFocus();
                } else {
                    jtf_desconto.setText("R$ 0,00");
                    jtf_desconto.setEditable(false);
                    jtf_desconto.setEnabled(false);
                    jtf_valor_pago.setEditable(true);
                    jtf_valor_pago.setEnabled(true);
                    jtf_valor_pago.requestFocus();
                }
                ///Faz alguma coisa interessante
            } else {
                jpf_senha.requestFocus();
                jpf_senha.setText("");
                jtf_login.setText("");
                jtf_desconto.setText("R$ 0,00");
                jtf_valor_pago.setText("R$ 0,00");
                jtf_desconto.setEditable(false);
                jtf_desconto.setEnabled(false);
                jtf_valor_pago.setEditable(false);
                jtf_valor_pago.setEnabled(false);
                jb_salvar.setEnabled(false);
            }
        }
    }

    private boolean validaLogin() {
        String msgERRO = "Preencha os campos obrigatórios:\n";

        if (jpf_senha.getPassword().equals("")) {
            msgERRO = msgERRO + " *Senha\n";
        }

        if (!msgERRO.equals("Preencha os campos obrigatórios:\n")) {
            JOptionPane.showMessageDialog(this, msgERRO);
            return false;
        } else {
            return true;
        }

    }

    public List<Usuario> usuarios;
    public static AcessoUsuario acesso;

    public boolean verificaLogin() {
        pool = new Pool();
        UsuarioDAO usuarioControl = new UsuarioDAO(pool);
        acesso = usuarioControl.verificarPermissao(jpf_senha.getText().trim(), "br.com.locadora.view.EntradaCaixaDevolucao");
//        System.out.println("Usuário responsável Caixa: " + acesso.getUsuario().getNome_usuario());
        try {
            //verifica a senha
            char[] senha = jpf_senha.getPassword();
            char[] senhaDoBanco = acesso.getUsuario().getSenha().toCharArray();

            // verifica o tamanho da senha
            if (senha.length != senhaDoBanco.length) {
                JOptionPane.showMessageDialog(null, "Senha incorreta");
                jtf_login.setText("");
                return false; // se for diferente, retorna falso
            } else {
                for (int i = 0; i < senha.length; i++) {
                    if (senha[i] != senhaDoBanco[i]) {
                        JOptionPane.showMessageDialog(null, "Senha incorreta");
                        jtf_login.setText("");
                        return false; // se for diferente, retorna falso
                    }
                }
            }

            return true;

        } catch (Exception e) {
            System.out.println("Senha incorreta na Entrada de Caixa Devolucao");
            return false;
        }
    }

    public void finalizarCaixa() {
        ArquivoConfiguracao conf = new ArquivoConfiguracao();

        //Envia a gravação da locação e envia o lancamento de caixa
        if (!conf.readPropertie("caixa").equals("")) {
            if (jb_logar.isEnabled() == true) {
                if (validaLogin()) {
                    if (verificaLogin()) {
                        if (janelapaiDevolucao != null) {

                            calculaRelocacao();
                            cadastrarDevolucao();

                            jpf_senha.setEnabled(false);
                            jb_logar.setEnabled(false);
                            jtf_valor_pago.setEnabled(false);
                            jtf_desconto.setEnabled(false);
                            jb_salvar.setEnabled(false);
                            jb_imprimir.setEnabled(true);
                            jb_imprimir.requestFocus();

                            DefaultTableModel tb_devolucao = (DefaultTableModel) janelapaiDevolucao.jtbl_devolucao.getModel();
                            int rows = tb_devolucao.getRowCount();
                            for (int i = rows - 1; i >= 0; i--) {
                                tb_devolucao.removeRow(i);
                            }
                            janelapaiDevolucao.jtf_codigo_cliente.setText("");
                            janelapaiDevolucao.jtf_nome_cliente.setText("");

                            janelapaiDevolucao.jtf_total_a_pagar.setText("R$ 0,00");
                            janelapaiDevolucao.jtf_saldo.setText("R$ 0,00");
                            janelapaiDevolucao.jtf_total_desconto_entrega_antecipada.setText("R$ 0,00");
                            janelapaiDevolucao.jl_lancamento_aberto.setText("Pendente: 0");
                            janelapaiDevolucao.setTitle("Atendimento Devolução");

                        }
                    }
                }

            }
        } else {
            JOptionPane.showMessageDialog(null, "Caixa padrão não definido. Favor verificar");
        }
    }

    public void calculaRelocacao() {
        pool = new Pool();
        LocacaoDAO locaDAO = new LocacaoDAO(pool);
        List<ItemLocacao> itensRelocacao = AtendimentoDevolucao.itensDevolucao;
        List<ItemLocacao> itensGravarRelocao = new ArrayList<ItemLocacao>();
        for (int i = 0; i < itensRelocacao.size(); i++) {
            if (itensRelocacao.get(i).getDias_multa() > 0) {
                itensGravarRelocao.add(itensRelocacao.get(i));
            }
        }

        locaDAO.salvarRelocacao(itensGravarRelocao);

    }

    public void acionarAtalho(java.awt.event.KeyEvent evt) {
        if (evt.getKeyCode() == KeyEvent.VK_F10) {
            jb_salvar.doClick();
        }
        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            retornaJanelaPai();
        }
    }

    private void imprimir() {
        Usuario usuario = acesso.getUsuario();
        Printer imprimir = new Printer();
        imprimir.comprovanteDevolucao(itens, AtendimentoDevolucao.dependente, usuario, lancamento);
        String nome_arquivo = "Imprimir/comprovanteDevolucao_" + janelapaiDevolucao.dependente.getNome_dependente() + ".txt";
        if (imprimir.imprimirArquivo(nome_arquivo)) {
            //Desabilita para não haver mais alteração

            jtf_valor_pago.setEditable(false);
            jtf_desconto.setEditable(false);
            //Fechar janela após impressão

            retornaJanelaPai();

            File arquivo = new File(nome_arquivo);
            arquivo.deleteOnExit();
            arquivo.delete();
        }
    }

    public void retornaJanelaPai() {
        this.setVisible(false);
        if (janelapaiDevolucao != null) {
            String nome_arquivo = "Imprimir/comprovanteLocacao_" + janelapaiDevolucao.dependente.getNome_dependente() + ".txt";
            File arquivo = new File(nome_arquivo);
            arquivo.deleteOnExit();
            arquivo.delete();

            janelapaiDevolucao.setStatusTela(true);
            janelapaiDevolucao.jtf_codigo_objeto_devolucao.requestFocus();
        }
    }

    public void recalcularValores() {
        Moeda moeda = new Moeda();

        Double saldo = moeda.getPrecoFormato(janelapaiDevolucao.jtf_saldo.getText());
        Double total_relocacao = moeda.getPrecoFormato(janelapaiDevolucao.jtf_valor_total_relocacao.getText());
        Double desconto_entrega_antecipada = moeda.getPrecoFormato(janelapaiDevolucao.jtf_total_desconto_entrega_antecipada.getText());
        Double desconto = moeda.getPrecoFormato(jtf_desconto.getText());
        Double valor_total_a_pagar = moeda.getPrecoFormato(janelapaiDevolucao.jtf_total_a_pagar.getText());

        jtf_saldo.setText(moeda.setPrecoFormat(saldo.toString()));
        jtf_total_relocacao.setText(moeda.setPrecoFormat(total_relocacao.toString()));
        jtf_desconto_entrega_antecipada.setText(moeda.setPrecoFormat(desconto_entrega_antecipada.toString()));
        jtf_desconto.setText(moeda.setPrecoFormat(desconto.toString()));

        if (total_relocacao > 0 && total_relocacao > desconto) {
            jtf_desconto.setText(moeda.setPrecoFormat(desconto.toString()));
        } else if (total_relocacao <= desconto) {
            jtf_desconto.setText(moeda.setPrecoFormat(total_relocacao.toString()));
            desconto = moeda.getPrecoFormato(jtf_desconto.getText());
        }

        valor_total_a_pagar = valor_total_a_pagar - (desconto);
        if (valor_total_a_pagar > 0) {
            jtf_total_a_pagar.setText(moeda.setPrecoFormat(valor_total_a_pagar.toString()));
        } else {
            valor_total_a_pagar = 0.00;
            jtf_total_a_pagar.setText(moeda.setPrecoFormat(valor_total_a_pagar.toString()));
        }

        Double valor_pago = moeda.getPrecoFormato(jtf_valor_pago.getText());
        Double troco = valor_pago - valor_total_a_pagar;

        System.out.println("Total a pagar: " + valor_total_a_pagar);
        System.out.println("Valor pago: " + valor_pago);
        System.out.println("Troco: " + troco);

        jtf_valor_pago.setText(moeda.setPrecoFormat(valor_pago.toString()));
        if (troco > 0) {
            jtf_troco.setText(moeda.setPrecoFormat(troco.toString()));
            jtf_debito_atual.setText("R$ 0,00");
            jtf_debito_atual.setForeground(Color.black);
        } else if (troco < 0) {
            jtf_troco.setText("R$ 0,00");
            troco = troco * (-1);
            jtf_debito_atual.setText(moeda.setPrecoFormat(troco.toString()));
            jtf_debito_atual.setForeground(Color.RED);
        } else {
            jtf_troco.setText("R$ 0,00");
            jtf_debito_atual.setText("R$ 0,00");
            jtf_debito_atual.setForeground(Color.black);
        }

    }

    public void cadastrarDevolucao() {

        try {
            DevolucaoDAO devolucaoDAO;
            Locacao locacao = new Locacao();
            locacao.setDependente(janelapaiDevolucao.dependente);
            locacao.setUsuario(acesso.getUsuario());

            Double valor_pago;
            Double desconto;
            Double relocacao;
            Double troco;
            Double desconto_entrega_antecipada;

            moeda = new Moeda();
            valor_pago = moeda.getPrecoFormato(jtf_valor_pago.getText());
            desconto = moeda.getPrecoFormato(jtf_desconto.getText());
            relocacao = moeda.getPrecoFormato(jtf_total_relocacao.getText());
            desconto_entrega_antecipada = moeda.getPrecoFormato(jtf_desconto_entrega_antecipada.getText());
            troco = moeda.getPrecoFormato(jtf_troco.getText());
            valor_pago = valor_pago - troco;
            Double valor_total_a_pagar = moeda.getPrecoFormato(jtf_total_a_pagar.getText());
            Double saldo = 0.00;
            if (jtf_saldo.getForeground().equals(Color.BLACK)) {
                saldo = moeda.getPrecoFormato(jtf_saldo.getText());
            }

            ArquivoConfiguracao conf = new ArquivoConfiguracao();

            TipoServico tipoServico;
            lancamento = new Lancamento();
            lancamento.setValor_total(relocacao);
            
            lancamento.setSaldo_dia(saldo);
            lancamento.setDesconto(desconto);
            lancamento.setDesconto_entrega_antecipada(desconto_entrega_antecipada);
            lancamento.setValor_pago(moeda.getPrecoFormato(jtf_valor_pago.getText()));
            lancamento.setTroco(troco);
            lancamento.setValor_total_a_pagar(valor_total_a_pagar);
            
            
            lancamento.setDependente(janelapaiDevolucao.dependente);
            tipoServico = new TipoServico();
            tipoServico.setCodigo_tipo_servico(2);
            lancamento.setTipoServico(tipoServico);
            lancamento.setUsuario(acesso.getUsuario());
            lancamento.setCaixa(Integer.parseInt(conf.readPropertie("caixa")));
            lancamento.setLocacao(new Locacao());
            lancamento.setDevolucao(new Devolucao());
            lancamento.setVenda(new Venda());

            pool = new Pool();
            lancamentoDAO = new LancamentoDAO(pool);
            lancamento = lancamentoDAO.salvarLancamento(lancamento);

            List<ItemLancamento> itensLancamento = new ArrayList<>();
            ItemLancamento itemLancamento;

            Calendar data_atual = Calendar.getInstance();

            if (desconto > 0) {
                itemLancamento = new ItemLancamento();
                itemLancamento.setData_lancamento(data_atual.getTime());
                itemLancamento.setLancamento(lancamento);
                itemLancamento.setValor_lancamento(desconto);
                tipoServico = new TipoServico();
                tipoServico.setCodigo_tipo_servico(8);
                itemLancamento.setTipoServico(tipoServico);
                itemLancamento.setCaixa(Integer.parseInt(conf.readPropertie("caixa")));
                itemLancamento.setUsuario(acesso.getUsuario());
                itensLancamento.add(itemLancamento);
                relocacao = relocacao - desconto;
            }
            if (desconto_entrega_antecipada > 0) {
                if (desconto_entrega_antecipada > relocacao && relocacao > 0) {
                    itemLancamento = new ItemLancamento();
                    itemLancamento.setData_lancamento(data_atual.getTime());
                    itemLancamento.setLancamento(lancamento);
                    itemLancamento.setValor_lancamento(relocacao);
                    tipoServico = new TipoServico();
                    tipoServico.setCodigo_tipo_servico(14);
                    itemLancamento.setTipoServico(tipoServico);
                    itemLancamento.setCaixa(Integer.parseInt(conf.readPropertie("caixa")));
                    itemLancamento.setUsuario(acesso.getUsuario());
                    itensLancamento.add(itemLancamento);
                    desconto_entrega_antecipada = desconto_entrega_antecipada - relocacao;
                    relocacao = 0.00;
                } else if (desconto_entrega_antecipada <= relocacao && relocacao > 0) {
                    itemLancamento = new ItemLancamento();
                    itemLancamento.setData_lancamento(data_atual.getTime());
                    itemLancamento.setLancamento(lancamento);
                    itemLancamento.setValor_lancamento(desconto_entrega_antecipada);
                    tipoServico = new TipoServico();
                    tipoServico.setCodigo_tipo_servico(14);
                    itemLancamento.setTipoServico(tipoServico);
                    itemLancamento.setCaixa(Integer.parseInt(conf.readPropertie("caixa")));
                    itemLancamento.setUsuario(acesso.getUsuario());
                    itensLancamento.add(itemLancamento);
                    relocacao = relocacao - desconto_entrega_antecipada;
                    desconto_entrega_antecipada = 0.00;
                }
            }

            if (desconto_entrega_antecipada > 0) {
                lancamento = new Lancamento();
                lancamento.setValor_total(desconto_entrega_antecipada);
                lancamento.setDependente(janelapaiDevolucao.dependente);
                tipoServico = new TipoServico();
                tipoServico.setCodigo_tipo_servico(9);
                lancamento.setTipoServico(tipoServico);
                lancamento.setUsuario(acesso.getUsuario());
                lancamento.setCaixa(Integer.parseInt(conf.readPropertie("caixa")));
                lancamento.setLocacao(new Locacao());
                lancamento.setDevolucao(new Devolucao());
                lancamento.setVenda(new Venda());

                pool = new Pool();
                lancamentoDAO = new LancamentoDAO(pool);
                lancamentoDAO.salvarLancamento(lancamento);
            }

            pool = new Pool();
            List<Lancamento> lancamentos = new ArrayList<Lancamento>();
            LancamentoDAO lancamentoDAO = new LancamentoDAO(pool);
            lancamentos = lancamentoDAO.getLancamentos(janelapaiDevolucao.dependente.getCliente());

            if (saldo >= relocacao && relocacao > 0) {
                for (int i = 0; i < lancamentos.size(); i++) {
                    if (lancamentos.get(i).getSaldo() >= relocacao) {
                        //Diminui do Saldo
                        itemLancamento = new ItemLancamento();
                        itemLancamento.setData_lancamento(data_atual.getTime());
                        itemLancamento.setLancamento(lancamentos.get(i));
                        itemLancamento.setValor_lancamento(relocacao);
                        tipoServico = new TipoServico();
                        tipoServico.setCodigo_tipo_servico(13);
                        itemLancamento.setTipoServico(tipoServico);
                        itemLancamento.setCaixa(Integer.parseInt(conf.readPropertie("caixa")));
                        itemLancamento.setUsuario(acesso.getUsuario());
                        itensLancamento.add(itemLancamento);
                        //Lança pagamento
                        itemLancamento = new ItemLancamento();
                        itemLancamento.setData_lancamento(data_atual.getTime());
                        itemLancamento.setLancamento(lancamento);
                        itemLancamento.setValor_lancamento(relocacao);
                        tipoServico = new TipoServico();
                        tipoServico.setCodigo_tipo_servico(13);
                        itemLancamento.setTipoServico(tipoServico);
                        itemLancamento.setCaixa(Integer.parseInt(conf.readPropertie("caixa")));
                        itemLancamento.setUsuario(acesso.getUsuario());
                        itensLancamento.add(itemLancamento);
                        break;
                    } else if (lancamentos.get(i).getSaldo() < relocacao && lancamentos.get(i).getSaldo() > 0) {
                        //Diminui do Saldo
                        itemLancamento = new ItemLancamento();
                        itemLancamento.setData_lancamento(data_atual.getTime());
                        itemLancamento.setLancamento(lancamentos.get(i));
                        itemLancamento.setValor_lancamento(lancamentos.get(i).getSaldo());
                        tipoServico = new TipoServico();
                        tipoServico.setCodigo_tipo_servico(13);
                        itemLancamento.setTipoServico(tipoServico);
                        itemLancamento.setCaixa(Integer.parseInt(conf.readPropertie("caixa")));
                        itemLancamento.setUsuario(acesso.getUsuario());
                        itensLancamento.add(itemLancamento);
                        //Lança pagamento
                        itemLancamento = new ItemLancamento();
                        itemLancamento.setData_lancamento(data_atual.getTime());
                        itemLancamento.setLancamento(lancamento);
                        itemLancamento.setValor_lancamento(lancamentos.get(i).getSaldo());
                        tipoServico = new TipoServico();
                        tipoServico.setCodigo_tipo_servico(13);
                        itemLancamento.setTipoServico(tipoServico);
                        itemLancamento.setCaixa(Integer.parseInt(conf.readPropertie("caixa")));
                        itemLancamento.setUsuario(acesso.getUsuario());
                        itensLancamento.add(itemLancamento);
                        lancamentos.get(i).setSaldo(lancamentos.get(i).getSaldo() - relocacao);
                        relocacao = relocacao - lancamentos.get(i).getSaldo();
                    }
                }
            } else if (saldo < relocacao && relocacao > 0) {
                for (int i = 0; i < lancamentos.size(); i++) {
                    if (lancamentos.get(i).getSaldo() < relocacao && lancamentos.get(i).getSaldo() > 0) {
                        //Diminui do Saldo
                        itemLancamento = new ItemLancamento();
                        itemLancamento.setData_lancamento(data_atual.getTime());
                        itemLancamento.setLancamento(lancamentos.get(i));
                        itemLancamento.setValor_lancamento(lancamentos.get(i).getSaldo());
                        tipoServico = new TipoServico();
                        tipoServico.setCodigo_tipo_servico(13);
                        itemLancamento.setTipoServico(tipoServico);
                        itemLancamento.setCaixa(Integer.parseInt(conf.readPropertie("caixa")));
                        itemLancamento.setUsuario(acesso.getUsuario());
                        itensLancamento.add(itemLancamento);
                        //Lança pagamento
                        itemLancamento = new ItemLancamento();
                        itemLancamento.setData_lancamento(data_atual.getTime());
                        itemLancamento.setLancamento(lancamento);
                        itemLancamento.setValor_lancamento(lancamentos.get(i).getSaldo());
                        tipoServico = new TipoServico();
                        tipoServico.setCodigo_tipo_servico(13);
                        itemLancamento.setTipoServico(tipoServico);
                        itemLancamento.setCaixa(Integer.parseInt(conf.readPropertie("caixa")));
                        itemLancamento.setUsuario(acesso.getUsuario());
                        itensLancamento.add(itemLancamento);
                        lancamentos.get(i).setSaldo(lancamentos.get(i).getSaldo() - relocacao);
                        relocacao = relocacao - lancamentos.get(i).getSaldo();
                    }
                }
            }

            if (valor_pago > 0) {
                itemLancamento = new ItemLancamento();
                itemLancamento.setData_lancamento(data_atual.getTime());
                itemLancamento.setLancamento(lancamento);
                itemLancamento.setValor_lancamento(valor_pago);
                tipoServico = new TipoServico();
                tipoServico.setCodigo_tipo_servico(7);
                itemLancamento.setTipoServico(tipoServico);
                itemLancamento.setCaixa(Integer.parseInt(conf.readPropertie("caixa")));
                itemLancamento.setUsuario(acesso.getUsuario());
                itensLancamento.add(itemLancamento);
            }

            pool = new Pool();
            lancamentoDAO = new LancamentoDAO(pool);
            lancamentoDAO.salvarItemLancamento(itensLancamento);

            List<ItemLocacao> itens = new ArrayList();
            ItemLocacao itemDevolve;
            Copia copia;
            for (int i = 0; i < AtendimentoDevolucao.jtbl_devolucao.getRowCount(); i++) {

                itemDevolve = new ItemLocacao();
                copia = new Copia();
                copia.setCodigo_copia(AtendimentoDevolucao.itensDevolucao.get(i).getCopia().getCodigo_copia());
                copia.setStatus("0");
                itemDevolve.setCopia(copia);
                itemDevolve.setCodigo_item_locacao(AtendimentoDevolucao.itensDevolucao.get(i).getCodigo_item_locacao());

                Date data = new Date();
                data.setDate(data.getDate());

                AtendimentoDevolucao.itensDevolucao.get(i).setData_devolucao(data);
                System.out.println("Data Prevista: " + AtendimentoDevolucao.itensDevolucao.get(i).getData_prevista());
                itens.add(itemDevolve);

                pool = new Pool();
                CopiaDAO copiaDAO = new CopiaDAO(pool);
                copiaDAO.alterarStatusFilme(itemDevolve.getCopia());
                pool = new Pool();
                LocacaoDAO locacaoDAO = new LocacaoDAO(pool);
                locacaoDAO.salvarDevolucao(itens);

            }
            EntradaCaixaDevolucao.itens = AtendimentoDevolucao.itensDevolucao;
        } catch (NumberFormatException e) {
            System.out.println("Valor inválido: " + e.getMessage());

            e.printStackTrace();
        } catch (SQLException ex) {
            Logger.getLogger(EntradaCaixaDevolucao.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
