package br.com.locadora.view;

import br.com.locadora.conexao.InterfacePool;
import br.com.locadora.conexao.Pool;
import br.com.locadora.conexao.PoolStation;
import br.com.locadora.model.bean.AcessoUsuario;
import br.com.locadora.model.bean.Usuario;
import br.com.locadora.model.dao.UsuarioDAO;
import br.com.locadora.util.ArquivoConfiguracao;
import br.com.locadora.util.TemaInterface;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

public class TelaPrincipal extends javax.swing.JFrame {

    public SiscomLocadora janelaPai;
    public SiscomLocadora janelaLogin;
    public static Usuario usuario;
    public SiscomLocadora loginInicia;
    public AtendimentoLocacao atendimentoLocacao;
    public AtendimentoDevolucao atendimentoDevolucao;
    public AtendimentoVenda atendimentoVenda;
    public Financeiro financeiro;
    public MenuCliente menuCliente;
    public MenuDiaria menuDiaria;
    public MenuLegenda menuLegenda;
    public MenuProduto menuProduto;
    public MenuIdioma menuIdioma;
    public MenuObjeto menuObjeto;
    public MenuUsuario menuUsuario;
    public MenuFornecedor menuFornecedor;
    public MenuGenero menuGenero;
    public MenuCombo menuCombo;
    public FinanceiroReceber recebimento;
    public LancamentoOcorrencia ocorrenciaDanificado;
    public ControleAcesso acessoInterface;
    public InterfacePool pool;
    public PoolStation poolStation;
    public AcessoUsuario acesso;
    public Connection conn;
    
    public TelaPrincipal() {
        initComponents();
        TemaInterface.getInterface(this);
        this.setExtendedState(this.MAXIMIZED_BOTH);
        atendimentoLocacao = null;
        atendimentoDevolucao = null;
        
        poolStation = new PoolStation();
        conn = poolStation.getConnection();
            }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenuBar5 = new javax.swing.JMenuBar();
        jMenu9 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        jMenuBar6 = new javax.swing.JMenuBar();
        jMenu11 = new javax.swing.JMenu();
        jMenu12 = new javax.swing.JMenu();
        jMenuBar7 = new javax.swing.JMenuBar();
        jMenu13 = new javax.swing.JMenu();
        jMenu14 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        label_data = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        jlabel_usuario = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMB_Cadastro = new javax.swing.JMenuBar();
        menu_cadastros = new javax.swing.JMenu();
        jmi_cliente = new javax.swing.JMenuItem();
        jmi_produto = new javax.swing.JMenuItem();
        jmi_fornecedor = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenu15 = new javax.swing.JMenu();
        jmi_objeto = new javax.swing.JMenuItem();
        jmi_genero = new javax.swing.JMenuItem();
        jmi_diaria = new javax.swing.JMenuItem();
        jmi_gerar_codigo_barras = new javax.swing.JMenuItem();
        jmi_idioma = new javax.swing.JMenuItem();
        jmi_legenda = new javax.swing.JMenuItem();
        jmi_pacote_promocional = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        menuitem_sair = new javax.swing.JMenuItem();
        menu_movimentos2 = new javax.swing.JMenu();
        jmi_pagar_receber = new javax.swing.JMenuItem();
        menu_movimentos = new javax.swing.JMenu();
        jmi_atendimento_locacao = new javax.swing.JMenuItem();
        jmi_atendimento_devolucao = new javax.swing.JMenuItem();
        jmi_atendimento_venda = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jm_consulta = new javax.swing.JMenu();
        jmi_objeto_copia = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        menu_relatórios = new javax.swing.JMenu();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        menu_relatórios1 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jmi_backup = new javax.swing.JMenuItem();
        jm_caixa = new javax.swing.JMenu();
        jm_usuario = new javax.swing.JMenuItem();
        jm_acesso = new javax.swing.JMenuItem();
        jm_conf_impressora = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        menu_relatórios2 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();

        jFrame1.setName("jFrame1"); // NOI18N

        jMenuBar1.setName("jMenuBar1"); // NOI18N

        jMenu1.setText("File");
        jMenu1.setName("jMenu1"); // NOI18N
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenu2.setName("jMenu2"); // NOI18N
        jMenuBar1.add(jMenu2);

        jMenuBar2.setName("jMenuBar2"); // NOI18N

        jMenu3.setText("File");
        jMenu3.setName("jMenu3"); // NOI18N
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenu4.setName("jMenu4"); // NOI18N
        jMenuBar2.add(jMenu4);

        jMenuBar3.setName("jMenuBar3"); // NOI18N

        jMenu5.setText("File");
        jMenu5.setName("jMenu5"); // NOI18N
        jMenuBar3.add(jMenu5);

        jMenu6.setText("Edit");
        jMenu6.setName("jMenu6"); // NOI18N
        jMenuBar3.add(jMenu6);

        jMenuBar4.setName("jMenuBar4"); // NOI18N

        jMenu7.setText("File");
        jMenu7.setName("jMenu7"); // NOI18N
        jMenuBar4.add(jMenu7);

        jMenu8.setText("Edit");
        jMenu8.setName("jMenu8"); // NOI18N
        jMenuBar4.add(jMenu8);

        jMenuBar5.setName("jMenuBar5"); // NOI18N

        jMenu9.setText("File");
        jMenu9.setName("jMenu9"); // NOI18N
        jMenuBar5.add(jMenu9);

        jMenu10.setText("Edit");
        jMenu10.setName("jMenu10"); // NOI18N
        jMenuBar5.add(jMenu10);

        jMenuBar6.setName("jMenuBar6"); // NOI18N

        jMenu11.setText("File");
        jMenu11.setName("jMenu11"); // NOI18N
        jMenuBar6.add(jMenu11);

        jMenu12.setText("Edit");
        jMenu12.setName("jMenu12"); // NOI18N
        jMenuBar6.add(jMenu12);

        jMenuBar7.setName("jMenuBar7"); // NOI18N

        jMenu13.setText("File");
        jMenu13.setName("jMenu13"); // NOI18N
        jMenuBar7.add(jMenu13);

        jMenu14.setText("Edit");
        jMenu14.setName("jMenu14"); // NOI18N
        jMenuBar7.add(jMenu14);

        jMenuItem2.setText("jMenuItem2");
        jMenuItem2.setName("jMenuItem2"); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Siscom Locadora");
        setBackground(new java.awt.Color(11, 161, 179));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setIconImages(null);
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.TOOLKIT_EXCLUDE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        label_data.setName("label_data"); // NOI18N

        jToolBar1.setRollover(true);
        jToolBar1.setName("jToolBar1"); // NOI18N

        jlabel_usuario.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jlabel_usuario.setText("Usuário: ");
        jlabel_usuario.setName("jlabel_usuario"); // NOI18N
        jToolBar1.add(jlabel_usuario);

        jLabel4.setText("                                                                                                                                                                ");
        jLabel4.setName("jLabel4"); // NOI18N
        jToolBar1.add(jLabel4);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/locadora/image/BROADWAY-LOGO.png"))); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jMB_Cadastro.setName("jMB_Cadastro"); // NOI18N

        menu_cadastros.setMnemonic('C');
        menu_cadastros.setText("Cadastro");
        menu_cadastros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_cadastrosActionPerformed(evt);
            }
        });

        jmi_cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/locadora/image/cliente.png"))); // NOI18N
        jmi_cliente.setMnemonic('P');
        jmi_cliente.setText("Cliente");
        jmi_cliente.setName("jmi_cliente"); // NOI18N
        jmi_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_clienteActionPerformed(evt);
            }
        });
        menu_cadastros.add(jmi_cliente);

        jmi_produto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/locadora/image/produto.png"))); // NOI18N
        jmi_produto.setMnemonic('P');
        jmi_produto.setText("Produto");
        jmi_produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_produtoActionPerformed(evt);
            }
        });
        menu_cadastros.add(jmi_produto);

        jmi_fornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/locadora/image/fornecedor.png"))); // NOI18N
        jmi_fornecedor.setMnemonic('F');
        jmi_fornecedor.setText("Fornecedor");
        jmi_fornecedor.setName("jmi_fornecedor"); // NOI18N
        jmi_fornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_fornecedorActionPerformed(evt);
            }
        });
        jmi_fornecedor.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jmi_fornecedorAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        menu_cadastros.add(jmi_fornecedor);

        jSeparator4.setName("jSeparator4"); // NOI18N
        menu_cadastros.add(jSeparator4);

        jMenu15.setText("Locadora");
        jMenu15.setName("jMenu15"); // NOI18N

        jmi_objeto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/locadora/image/movies.png"))); // NOI18N
        jmi_objeto.setText("Objeto");
        jmi_objeto.setName("jmi_objeto"); // NOI18N
        jmi_objeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_objetoActionPerformed(evt);
            }
        });
        jMenu15.add(jmi_objeto);

        jmi_genero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/locadora/image/generos.png"))); // NOI18N
        jmi_genero.setText("Gênero");
        jmi_genero.setName("jmi_genero"); // NOI18N
        jmi_genero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_generoActionPerformed(evt);
            }
        });
        jMenu15.add(jmi_genero);

        jmi_diaria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/locadora/image/calendario.png"))); // NOI18N
        jmi_diaria.setText("Diária");
        jmi_diaria.setName("jmi_diaria"); // NOI18N
        jmi_diaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_diariaActionPerformed(evt);
            }
        });
        jMenu15.add(jmi_diaria);

        jmi_gerar_codigo_barras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/locadora/image/barcode.png"))); // NOI18N
        jmi_gerar_codigo_barras.setText("Gerar Código de Barras");
        jmi_gerar_codigo_barras.setName("jmi_gerar_codigo_barras"); // NOI18N
        jmi_gerar_codigo_barras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_gerar_codigo_barrasActionPerformed(evt);
            }
        });
        jMenu15.add(jmi_gerar_codigo_barras);

        jmi_idioma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/locadora/image/language-16.png"))); // NOI18N
        jmi_idioma.setText("Idioma");
        jmi_idioma.setName("jmi_idioma"); // NOI18N
        jmi_idioma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_idiomaActionPerformed(evt);
            }
        });
        jMenu15.add(jmi_idioma);

        jmi_legenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/locadora/image/Google-Buzz-16.png"))); // NOI18N
        jmi_legenda.setText("Legenda");
        jmi_legenda.setName("jmi_legenda"); // NOI18N
        jmi_legenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_legendaActionPerformed(evt);
            }
        });
        jMenu15.add(jmi_legenda);

        jmi_pacote_promocional.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/locadora/image/promotion.png"))); // NOI18N
        jmi_pacote_promocional.setText("Combo");
        jmi_pacote_promocional.setName("jmi_pacote_promocional"); // NOI18N
        jmi_pacote_promocional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_pacote_promocionalActionPerformed(evt);
            }
        });
        jMenu15.add(jmi_pacote_promocional);

        menu_cadastros.add(jMenu15);

        jSeparator2.setName("jSeparator2"); // NOI18N
        menu_cadastros.add(jSeparator2);

        menuitem_sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/locadora/image/sair.png"))); // NOI18N
        menuitem_sair.setText("Sair");
        menuitem_sair.setName("menuitem_sair"); // NOI18N
        menuitem_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitem_sairActionPerformed(evt);
            }
        });
        menu_cadastros.add(menuitem_sair);

        jMB_Cadastro.add(menu_cadastros);

        menu_movimentos2.setMnemonic('M');
        menu_movimentos2.setText("Financeiro");
        menu_movimentos2.setName("menu_movimentos2"); // NOI18N

        jmi_pagar_receber.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/locadora/image/finances_16x16.gif"))); // NOI18N
        jmi_pagar_receber.setText("Pagar / Receber");
        jmi_pagar_receber.setName("jmi_pagar_receber"); // NOI18N
        jmi_pagar_receber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_pagar_receberActionPerformed1(evt);
            }
        });
        menu_movimentos2.add(jmi_pagar_receber);

        jMB_Cadastro.add(menu_movimentos2);

        menu_movimentos.setMnemonic('M');
        menu_movimentos.setText("Atendimento");
        menu_movimentos.setName("menu_movimentos"); // NOI18N

        jmi_atendimento_locacao.setText("Locação");
        jmi_atendimento_locacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_atendimento_locacaoActionPerformed1(evt);
            }
        });
        menu_movimentos.add(jmi_atendimento_locacao);

        jmi_atendimento_devolucao.setText("Devolução");
        jmi_atendimento_devolucao.setName("jmi_atendimento_devolucao"); // NOI18N
        jmi_atendimento_devolucao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_atendimento_devolucaoActionPerformed1(evt);
            }
        });
        menu_movimentos.add(jmi_atendimento_devolucao);

        jmi_atendimento_venda.setText("Venda");
        jmi_atendimento_venda.setName("jmi_atendimento_venda"); // NOI18N
        jmi_atendimento_venda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_atendimento_vendaActionPerformed(evt);
            }
        });
        menu_movimentos.add(jmi_atendimento_venda);

        jMenuItem8.setText("Ocorrência Danificado");
        jMenuItem8.setName("jMenuItem8"); // NOI18N
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        menu_movimentos.add(jMenuItem8);

        jMB_Cadastro.add(menu_movimentos);

        jm_consulta.setText("Consulta");
        jm_consulta.setName("jm_consulta"); // NOI18N

        jmi_objeto_copia.setText("Objeto/Cópia");
        jmi_objeto_copia.setName("jmi_objeto_copia"); // NOI18N
        jmi_objeto_copia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_objeto_copiaActionPerformed(evt);
            }
        });
        jm_consulta.add(jmi_objeto_copia);

        jMenuItem16.setText("Fluxo de Caixa Diário");
        jMenuItem16.setName("jMenuItem16"); // NOI18N
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        jm_consulta.add(jMenuItem16);

        jMenuItem18.setText("Fluxo de Caixa Detalhado");
        jMenuItem18.setName("jMenuItem18"); // NOI18N
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem18ActionPerformed(evt);
            }
        });
        jm_consulta.add(jMenuItem18);

        jMenuItem4.setText("Locação em Aberto");
        jMenuItem4.setName("jMenuItem4"); // NOI18N
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jm_consulta.add(jMenuItem4);

        jMenuItem3.setText("Histórico de Locação");
        jMenuItem3.setName("jMenuItem3"); // NOI18N
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jm_consulta.add(jMenuItem3);

        jMenuItem11.setText("Ocorrências Danificado");
        jMenuItem11.setName("jMenuItem11"); // NOI18N
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jm_consulta.add(jMenuItem11);

        jMB_Cadastro.add(jm_consulta);

        menu_relatórios.setMnemonic('R');
        menu_relatórios.setText("Relatório");
        menu_relatórios.setName("menu_relatórios"); // NOI18N
        menu_relatórios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_relatóriosActionPerformed(evt);
            }
        });

        jMenuItem19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/locadora/image/report.png"))); // NOI18N
        jMenuItem19.setText("Relatórios Locação");
        jMenuItem19.setName("jMenuItem19"); // NOI18N
        jMenuItem19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem19ActionPerformed(evt);
            }
        });
        menu_relatórios.add(jMenuItem19);

        jMenuItem20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/locadora/image/report.png"))); // NOI18N
        jMenuItem20.setText("Relatórios Venda");
        jMenuItem20.setName("jMenuItem20"); // NOI18N
        jMenuItem20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem20ActionPerformed(evt);
            }
        });
        menu_relatórios.add(jMenuItem20);

        jMB_Cadastro.add(menu_relatórios);

        menu_relatórios1.setMnemonic('R');
        menu_relatórios1.setText("Utilitário");
        menu_relatórios1.setName("menu_relatórios1"); // NOI18N
        menu_relatórios1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_relatórios1ActionPerformed(evt);
            }
        });

        jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/locadora/image/calculadora.png"))); // NOI18N
        jMenuItem9.setText("Calculadora ");
        jMenuItem9.setName("jMenuItem9"); // NOI18N
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed1(evt);
            }
        });
        menu_relatórios1.add(jMenuItem9);

        jmi_backup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/locadora/image/backup.png"))); // NOI18N
        jmi_backup.setText("Backup");
        jmi_backup.setName("jmi_backup"); // NOI18N
        jmi_backup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_backupActionPerformed(evt);
            }
        });
        menu_relatórios1.add(jmi_backup);

        jMB_Cadastro.add(menu_relatórios1);

        jm_caixa.setText("Configuração");
        jm_caixa.setName("jm_caixa"); // NOI18N

        jm_usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/locadora/image/user.png"))); // NOI18N
        jm_usuario.setText("Usuário");
        jm_usuario.setName("jm_usuario"); // NOI18N
        jm_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_usuarioActionPerformed(evt);
            }
        });
        jm_caixa.add(jm_usuario);

        jm_acesso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/locadora/image/acesso.gif"))); // NOI18N
        jm_acesso.setText("Controle de Acessos");
        jm_acesso.setName("jm_acesso"); // NOI18N
        jm_acesso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_acessoActionPerformed(evt);
            }
        });
        jm_caixa.add(jm_acesso);

        jm_conf_impressora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/locadora/image/printer.png"))); // NOI18N
        jm_conf_impressora.setText("Configurar Impressora");
        jm_conf_impressora.setName("jm_conf_impressora"); // NOI18N
        jm_conf_impressora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_conf_impressoraActionPerformed(evt);
            }
        });
        jm_caixa.add(jm_conf_impressora);

        jMenuItem17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/locadora/image/caixa.png"))); // NOI18N
        jMenuItem17.setText("Configurar Caixa");
        jMenuItem17.setName("jMenuItem17"); // NOI18N
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        jm_caixa.add(jMenuItem17);

        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/locadora/image/Travel.png"))); // NOI18N
        jMenuItem7.setText("Configurar Feriado");
        jMenuItem7.setName("jMenuItem7"); // NOI18N
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jm_caixa.add(jMenuItem7);

        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/locadora/image/license-manager.png"))); // NOI18N
        jMenuItem5.setText("Controle de Licenças");
        jMenuItem5.setName("jMenuItem5"); // NOI18N
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jm_caixa.add(jMenuItem5);

        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/locadora/image/servidor.png"))); // NOI18N
        jMenuItem6.setText("Configurar Servidor");
        jMenuItem6.setName("jMenuItem6"); // NOI18N
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jm_caixa.add(jMenuItem6);

        jMenuItem12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/locadora/image/utilities-system-monitor.png"))); // NOI18N
        jMenuItem12.setText("Log Info Sistema");
        jMenuItem12.setName("jMenuItem12"); // NOI18N
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jm_caixa.add(jMenuItem12);

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/locadora/image/change.png"))); // NOI18N
        jMenuItem1.setText("Trocar de usuário");
        jMenuItem1.setName("jMenuItem1"); // NOI18N
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jm_caixa.add(jMenuItem1);

        jMB_Cadastro.add(jm_caixa);

        menu_relatórios2.setMnemonic('R');
        menu_relatórios2.setText("Ajuda");
        menu_relatórios2.setName("menu_relatórios2"); // NOI18N
        menu_relatórios2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_relatórios2ActionPerformed(evt);
            }
        });

        jMenuItem10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/locadora/image/help.png"))); // NOI18N
        jMenuItem10.setText("Help!");
        jMenuItem10.setName("jMenuItem10"); // NOI18N
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        menu_relatórios2.add(jMenuItem10);

        jMB_Cadastro.add(menu_relatórios2);

        setJMenuBar(jMB_Cadastro);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 1340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(352, 352, 352)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void menuitem_entradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitem_entradaActionPerformed

    }//GEN-LAST:event_menuitem_entradaActionPerformed

    private void jmi_produtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_produtoActionPerformed
        pool = new Pool();
        UsuarioDAO usuarioControl = new UsuarioDAO(pool);
        ArquivoConfiguracao conf = new ArquivoConfiguracao();
        acesso = usuarioControl.permissaoInterface(conf.readPropertie("login"), "br.com.locadora.view.MenuProduto");
        try {
            if (acesso.getLer() == false) {
                JOptionPane.showMessageDialog(null, "Usuário sem permissão. Consultar o administrador");
            } else if (acesso.getLer() == true) {
                menuProduto = new MenuProduto();
                menuProduto.janelapai = this;
                menuProduto.setVisible(true);
//                setStatusTela(false);
                menuProduto.acesso = acesso;
            } else {
                JOptionPane.showMessageDialog(null, "Usuário sem permissão. Consultar o administrador");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage() + " Entre em contato com o administrador do sistema.");
        }


    }//GEN-LAST:event_jmi_produtoActionPerformed

    private void jmi_atendimento_locacaoActionPerformed1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_atendimento_locacaoActionPerformed1
        pool = new Pool();
        UsuarioDAO usuarioControl = new UsuarioDAO(pool);
        ArquivoConfiguracao conf = new ArquivoConfiguracao();
        acesso = usuarioControl.permissaoInterface(conf.readPropertie("login"), "br.com.locadora.view.AtendimentoLocacao");

        try {
            if (acesso.getEscrever() == false) {
                JOptionPane.showMessageDialog(null, "Usuário sem permissão. Consultar o administrador");
            } else if (acesso.getEscrever() == true) {
                if (atendimentoLocacao == null) {
                    atendimentoLocacao = new AtendimentoLocacao();
                    atendimentoLocacao.acesso = acesso;
                    atendimentoLocacao.setVisible(true);
                    atendimentoLocacao.janelapai = this;
                } else {
                    atendimentoLocacao.setVisible(true);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Usuário sem permissão. Consultar o administrador");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage() + " Entre em contato com o administrador do sistema.");
        }

    }//GEN-LAST:event_jmi_atendimento_locacaoActionPerformed1

    private void menu_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_sairActionPerformed
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_menu_sairActionPerformed

    private void jmi_generoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_generoActionPerformed
        pool = new Pool();
        UsuarioDAO usuarioControl = new UsuarioDAO(pool);
        ArquivoConfiguracao conf = new ArquivoConfiguracao();
        acesso = usuarioControl.permissaoInterface(conf.readPropertie("login"), "br.com.locadora.view.MenuGenero");

        try {
            if (acesso.getLer() == false) {
                JOptionPane.showMessageDialog(null, "Usuário sem permissão. Consultar o administrador");
            } else if (acesso.getLer() == true) {
                menuGenero = new MenuGenero();
                menuGenero.janelapai = this;
                menuGenero.setVisible(true);
//                setStatusTela(false);
                menuGenero.acesso = acesso;
            } else {
                JOptionPane.showMessageDialog(null, "Usuário sem permissão. Consultar o administrador");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage() + " Entre em contato com o administrador do sistema.");
        }


    }//GEN-LAST:event_jmi_generoActionPerformed

    private void menu_cadastrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_cadastrosActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_menu_cadastrosActionPerformed

    private void menuitem_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitem_sairActionPerformed
        System.exit(0);
        // TODO add your handling code here:
}//GEN-LAST:event_menuitem_sairActionPerformed

    private void jmi_fornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_fornecedorActionPerformed
        pool = new Pool();
        UsuarioDAO usuarioControl = new UsuarioDAO(pool);
        ArquivoConfiguracao conf = new ArquivoConfiguracao();
        acesso = usuarioControl.permissaoInterface(conf.readPropertie("login"), "br.com.locadora.view.MenuFornecedor");
        try {
            if (acesso.getLer() == false) {
                JOptionPane.showMessageDialog(null, "Usuário sem permissão. Consultar o administrador");
            } else if (acesso.getLer() == true) {
                menuFornecedor = new MenuFornecedor();
                menuFornecedor.janelapai = this;
                menuFornecedor.setVisible(true);
//                setStatusTela(false);
                menuFornecedor.acesso = acesso;
            } else {
                JOptionPane.showMessageDialog(null, "Usuário sem permissão. Consultar o administrador");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage() + " Entre em contato com o administrador do sistema.");
            ex.printStackTrace();
        }


    }//GEN-LAST:event_jmi_fornecedorActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        System.exit(0);
        try {
            conn.close();
            // TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowClosed

    private void jmi_fornecedorAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jmi_fornecedorAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jmi_fornecedorAncestorAdded

    private void timer1OnTime(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timer1OnTime


    }//GEN-LAST:event_timer1OnTime

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void jm_acessoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_acessoActionPerformed
        pool = new Pool();
        UsuarioDAO usuarioControl = new UsuarioDAO(pool);
        ArquivoConfiguracao conf = new ArquivoConfiguracao();
        acesso = usuarioControl.permissaoInterface(conf.readPropertie("login"), "br.com.locadora.view.ControleAcesso");
        try {
            if (acesso.getSuper_usuario() == false) {
                JOptionPane.showMessageDialog(null, "Usuário sem permissão. Consultar o administrador");
            } else if (acesso.getSuper_usuario() == true) {
                acessoInterface = new ControleAcesso();
                acessoInterface.janelapai = this;
                acessoInterface.setVisible(true);
//                setStatusTela(false);
                acessoInterface.acesso = acesso;
            } else {
                JOptionPane.showMessageDialog(null, "Usuário sem permissão. Consultar o administrador");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage() + " Entre em contato com o administrador do sistema.");
        }

    }//GEN-LAST:event_jm_acessoActionPerformed

    private void menu_relatóriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_relatóriosActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_menu_relatóriosActionPerformed

    private void menu_relatórios1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_relatórios1ActionPerformed
        System.exit(0);
        loginInicia = new SiscomLocadora();
        loginInicia.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_menu_relatórios1ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        try {
            Runtime.getRuntime().exec("calc");
        } catch (IOException exc) {
        }        // TODO add your handling code here:
}//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        JOptionPane.showMessageDialog(null, "Suporte de Desenvolvimento - Alencar Buriti (62) 8100-0456 - alencarburiti@gmail.com");
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void menu_relatórios2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_relatórios2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menu_relatórios2ActionPerformed

    private void jMenuItem9ActionPerformed1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed1
        try {
            Runtime.getRuntime().exec("calc");
        } catch (IOException exc) {
        }          // TODO add your handling code here:
}//GEN-LAST:event_jMenuItem9ActionPerformed1

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        try {
            conn.close();
        } catch (SQLException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
        loginInicia = new SiscomLocadora();
        loginInicia.show();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

private void jmi_backupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_backupActionPerformed
    EfetuaBackup backup = new EfetuaBackup();
    backup.setVisible(true);
    backup.janelapai = this;
}//GEN-LAST:event_jmi_backupActionPerformed

    private void jmi_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_clienteActionPerformed
        pool = new Pool();
        UsuarioDAO usuarioControl = new UsuarioDAO(pool);
        ArquivoConfiguracao conf = new ArquivoConfiguracao();
        acesso = usuarioControl.permissaoInterface(conf.readPropertie("login"), "br.com.locadora.view.MenuCliente");
        try {
            if (acesso.getLer() == false) {
                JOptionPane.showMessageDialog(null, "Usuário sem permissão. Consultar o administrador");
            } else if (acesso.getLer() == true) {
                menuCliente = new MenuCliente();
                menuCliente.janelapai = this;
                menuCliente.setVisible(true);
//                this.setStatusTela(false);
                menuCliente.acesso = acesso;
            } else {
                JOptionPane.showMessageDialog(null, "Usuário sem permissão. Consultar o administrador");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage() + " Entre em contato com o administrador do sistema.");
        }
    }//GEN-LAST:event_jmi_clienteActionPerformed

    private void jmi_diariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_diariaActionPerformed
        pool = new Pool();
        UsuarioDAO usuarioControl = new UsuarioDAO(pool);
        ArquivoConfiguracao conf = new ArquivoConfiguracao();
        acesso = usuarioControl.permissaoInterface(conf.readPropertie("login"), "br.com.locadora.view.MenuDiaria");

        try {
            if (acesso.getLer() == false) {
                JOptionPane.showMessageDialog(null, "Usuário sem permissão. Consultar o administrador");
            } else if (acesso.getLer() == true) {
                menuDiaria = new MenuDiaria();
                menuDiaria.janelapai = this;
                menuDiaria.setVisible(true);
//                setStatusTela(false);
                menuDiaria.acesso = acesso;
            } else {
                JOptionPane.showMessageDialog(null, "Usuário sem permissão. Consultar o administrador");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage() + " Entre em contato com o administrador do sistema.");
        }

    }//GEN-LAST:event_jmi_diariaActionPerformed

    private void jmi_objetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_objetoActionPerformed
        pool = new Pool();
        UsuarioDAO usuarioControl = new UsuarioDAO(pool);
        ArquivoConfiguracao conf = new ArquivoConfiguracao();
        acesso = usuarioControl.permissaoInterface(conf.readPropertie("login"), "br.com.locadora.view.MenuObjeto");
        try {
            if (acesso.getLer() == false) {
                JOptionPane.showMessageDialog(null, "Usuário sem permissão. Consultar o administrador");
            } else if (acesso.getLer() == true) {
                menuObjeto = new MenuObjeto();
                menuObjeto.janelapai = this;
                menuObjeto.setVisible(true);
                menuObjeto.acesso = acesso;
            } else {
                JOptionPane.showMessageDialog(null, "Usuário sem permissão. Consultar o administrador");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage() + " Entre em contato com o administrador do sistema.");
        }
    }//GEN-LAST:event_jmi_objetoActionPerformed

    private void jmi_idiomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_idiomaActionPerformed
        pool = new Pool();
        UsuarioDAO usuarioControl = new UsuarioDAO(pool);
        ArquivoConfiguracao conf = new ArquivoConfiguracao();
        acesso = usuarioControl.permissaoInterface(conf.readPropertie("login"), "br.com.locadora.view.MenuIdioma");
        try {
            if (acesso.getLer() == false) {
                JOptionPane.showMessageDialog(null, "Usuário sem permissão. Consultar o administrador");
            } else if (acesso.getLer() == true) {
                menuIdioma = new MenuIdioma();
                menuIdioma.janelapai = this;
                menuIdioma.setVisible(true);
//                setStatusTela(false);
                menuIdioma.acesso = acesso;
            } else {
                JOptionPane.showMessageDialog(null, "Usuário sem permissão. Consultar o administrador");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage() + " Entre em contato com o administrador do sistema.");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jmi_idiomaActionPerformed

    private void jmi_legendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_legendaActionPerformed
        pool = new Pool();
        UsuarioDAO usuarioControl = new UsuarioDAO(pool);
        ArquivoConfiguracao conf = new ArquivoConfiguracao();
        acesso = usuarioControl.permissaoInterface(conf.readPropertie("login"), "br.com.locadora.view.MenuLegenda");
        try {
            if (acesso.getLer() == false) {
                JOptionPane.showMessageDialog(null, "Usuário sem permissão. Consultar o administrador");
            } else if (acesso.getLer() == true) {
                menuLegenda = new MenuLegenda();
                menuLegenda.janelapai = this;
                menuLegenda.setVisible(true);
//                setStatusTela(false);
                menuLegenda.acesso = acesso;
            } else {
                JOptionPane.showMessageDialog(null, "Usuário sem permissão. Consultar o administrador");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage() + " Entre em contato com o administrador do sistema.");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jmi_legendaActionPerformed

    private void jmi_gerar_codigo_barrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_gerar_codigo_barrasActionPerformed
        Bar bar = new Bar();
        bar.setVisible(true);
        bar.janelapai = this;
        bar.setLocationRelativeTo(null);
    }//GEN-LAST:event_jmi_gerar_codigo_barrasActionPerformed

    private void jmi_pagar_receberActionPerformed1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_pagar_receberActionPerformed1
        pool = new Pool();
        UsuarioDAO usuarioControl = new UsuarioDAO(pool);
        ArquivoConfiguracao conf = new ArquivoConfiguracao();
        acesso = usuarioControl.permissaoInterface(conf.readPropertie("login"), "br.com.locadora.view.Financeiro");
        try {
            if (acesso.getLer() == false) {
                JOptionPane.showMessageDialog(null, "Usuário sem permissão. Consultar o administrador");
            } else if (acesso.getLer() == true) {
                if (financeiro == null) {
                    financeiro = new Financeiro();
                    financeiro.janelapai = this;
                    financeiro.setVisible(true);
                    financeiro.acesso = acesso;
                } else {
                    financeiro.setVisible(true);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Usuário sem permissão. Consultar o administrador");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage() + " Entre em contato com o administrador do sistema.");
            ex.printStackTrace();
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jmi_pagar_receberActionPerformed1

    private void jm_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_usuarioActionPerformed
        pool = new Pool();
        UsuarioDAO usuarioControl = new UsuarioDAO(pool);
        ArquivoConfiguracao conf = new ArquivoConfiguracao();
        acesso = usuarioControl.permissaoInterface(conf.readPropertie("login"), "br.com.locadora.view.MenuUsuario");

        try {
            if (acesso.getSuper_usuario() == false) {
                JOptionPane.showMessageDialog(null, "Usuário sem permissão. Consultar o administrador");
            } else if (acesso.getSuper_usuario() == true) {
                menuUsuario = new MenuUsuario();
                menuUsuario.janelapai = this;
                menuUsuario.setVisible(true);
//                setStatusTela(false);
                menuUsuario.acesso = acesso;
            } else {
                JOptionPane.showMessageDialog(null, "Usuário sem permissão. Consultar o administrador");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage() + " Entre em contato com o administrador do sistema.");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jm_usuarioActionPerformed

    private void jmi_atendimento_devolucaoActionPerformed1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_atendimento_devolucaoActionPerformed1
        pool = new Pool();
        UsuarioDAO usuarioControl = new UsuarioDAO(pool);
        ArquivoConfiguracao conf = new ArquivoConfiguracao();
        acesso = usuarioControl.permissaoInterface(conf.readPropertie("login"), "br.com.locadora.view.AtendimentoDevolucao");

        try {
            if (acesso.getEscrever() == false) {
                JOptionPane.showMessageDialog(null, "Usuário sem permissão. Consultar o administrador");
            } else if (acesso.getEscrever() == true) {
                if (atendimentoDevolucao == null) {
                    atendimentoDevolucao = new AtendimentoDevolucao();
                    atendimentoDevolucao.janelapai = this;
                    atendimentoDevolucao.setVisible(true);
                    atendimentoDevolucao.acesso = acesso;
                } else {
                    atendimentoDevolucao.setVisible(true);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Usuário sem permissão. Consultar o administrador");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage() + " Entre em contato com o administrador do sistema.");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jmi_atendimento_devolucaoActionPerformed1

    private void jm_conf_impressoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_conf_impressoraActionPerformed
        ConfiguraImpressora conf = new ConfiguraImpressora();
        conf.setVisible(true);
        conf.janelapai = this;
        setStatusTela(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_jm_conf_impressoraActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        FluxodeCaixaDiario control = new FluxodeCaixaDiario();
        control.janelapai = this;
        control.setVisible(true);
        setStatusTela(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
        pool = new Pool();
        UsuarioDAO usuarioControl = new UsuarioDAO(pool);
        ArquivoConfiguracao conf = new ArquivoConfiguracao();
        acesso = usuarioControl.permissaoInterface(conf.readPropertie("login"), "br.com.locadora.view.ConfiguraCaixa");

        try {
            if (acesso.getSuper_usuario() == false) {
                JOptionPane.showMessageDialog(null, "Usuário sem permissão. Consultar o administrador");
            } else if (acesso.getSuper_usuario() == true) {
                ConfiguraCaixa caixa = new ConfiguraCaixa();
                caixa.setVisible(true);
//                setStatusTela(false);
                caixa.janelapai = this;
                caixa.acesso = acesso;
            } else {
                JOptionPane.showMessageDialog(null, "Usuário sem permissão. Consultar o administrador");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage() + " Entre em contato com o administrador do sistema.");
        }
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18ActionPerformed
        FluxodeCaixaDetalhado control = new FluxodeCaixaDetalhado();
        control.janelapai = this;
        control.setVisible(true);
        setStatusTela(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem18ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        LocacaoEmAberto locAberto = new LocacaoEmAberto();
        locAberto.janelapai = this;
        locAberto.setVisible(true);
        setStatusTela(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem19ActionPerformed
        MenuRelatorioLocacaoDevolucao menuRelatorio = new MenuRelatorioLocacaoDevolucao();
        menuRelatorio.janelapai = this;
        menuRelatorio.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem19ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
//        JOptionPane.showMessageDialog(null, "Em Construção");
        ControleLicenca controleLicenca = new ControleLicenca();
        controleLicenca.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jmi_atendimento_vendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_atendimento_vendaActionPerformed
        pool = new Pool();
        UsuarioDAO usuarioControl = new UsuarioDAO(pool);
        ArquivoConfiguracao conf = new ArquivoConfiguracao();
        acesso = usuarioControl.permissaoInterface(conf.readPropertie("login"), "br.com.locadora.view.AtendimentoVenda");

        try {
            if (acesso.getEscrever() == false) {
                JOptionPane.showMessageDialog(null, "Usuário sem permissão. Consultar o administrador");
            } else if (acesso.getEscrever() == true) {
                if (atendimentoVenda == null) {
                    atendimentoVenda = new AtendimentoVenda();
                    atendimentoVenda.acesso = acesso;
                    atendimentoVenda.setVisible(true);
                    atendimentoVenda.janelapai = this;
                } else {
                    atendimentoLocacao.setVisible(true);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Usuário sem permissão. Consultar o administrador");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage() + " Entre em contato com o administrador do sistema.");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jmi_atendimento_vendaActionPerformed

    private void jmi_pacote_promocionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_pacote_promocionalActionPerformed
        pool = new Pool();
        UsuarioDAO usuarioControl = new UsuarioDAO(pool);
        ArquivoConfiguracao conf = new ArquivoConfiguracao();
        acesso = usuarioControl.permissaoInterface(conf.readPropertie("login"), "br.com.locadora.view.MenuCombo");

        try {
            if (acesso.getEscrever() == false) {
                JOptionPane.showMessageDialog(null, "Usuário sem permissão. Consultar o administrador");
            } else if (acesso.getEscrever() == true) {
                if (menuCombo == null) {
                    menuCombo = new MenuCombo();
                    menuCombo.acesso = acesso;
                    menuCombo.setVisible(true);
                    menuCombo.janelapai = this;
                } else {
                    menuCombo.setVisible(true);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Usuário sem permissão. Consultar o administrador");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage() + " Entre em contato com o administrador do sistema.");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jmi_pacote_promocionalActionPerformed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        acionarAtalho(evt);
        // TODO add your handling code here:
    }//GEN-LAST:event_formKeyPressed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        HistoricoLocacao historicoLocacao = new HistoricoLocacao();
        historicoLocacao.janelapai = this;
        historicoLocacao.setVisible(true);
        setStatusTela(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        ConfiguraDB configuraDB = new ConfiguraDB();
        configuraDB.janelapai = this;
        configuraDB.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        ConfiguraFeriado configuraFeriado = new ConfiguraFeriado();
        configuraFeriado.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jmi_objeto_copiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_objeto_copiaActionPerformed
        ConsultaCopiaLocacao copiaCliente = new ConsultaCopiaLocacao();
        copiaCliente.janelapaiPrincipal = this;
        copiaCliente.setVisible(true);
        setStatusTela(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jmi_objeto_copiaActionPerformed

    private void jMenuItem20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem20ActionPerformed
        MenuRelatorioVenda menuRelatorioVenda = new MenuRelatorioVenda();
        menuRelatorioVenda.janelapai = this;
        menuRelatorioVenda.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem20ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        pool = new Pool();
        UsuarioDAO usuarioControl = new UsuarioDAO(pool);
        ArquivoConfiguracao conf = new ArquivoConfiguracao();
        acesso = usuarioControl.permissaoInterface(conf.readPropertie("login"), "br.com.locadora.view.AtendimentoOcorrencia");

        try {
            if (acesso.getEscrever() == false) {
                JOptionPane.showMessageDialog(null, "Usuário sem permissão. Consultar o administrador");
            } else if (acesso.getEscrever() == true) {
                if (ocorrenciaDanificado == null) {
                    ocorrenciaDanificado = new LancamentoOcorrencia();
                    ocorrenciaDanificado.acesso = acesso;                    
                    ocorrenciaDanificado.setVisible(true);
                    ocorrenciaDanificado.janelapai = this;
                } else {
                    ocorrenciaDanificado.setVisible(true);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Usuário sem permissão. Consultar o administrador");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage() + " Entre em contato com o administrador do sistema.");
        }        
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        ConsultarOcorrencia consultaOcorrencia = new ConsultarOcorrencia();
        consultaOcorrencia.janelapai = this;
        consultaOcorrencia.setVisible(true);
        setStatusTela(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        MenuLogSistema menuLogSistema = new MenuLogSistema();
        menuLogSistema.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new TelaPrincipal().setVisible(true);

            }
        });

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMB_Cadastro;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu15;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JMenuBar jMenuBar5;
    private javax.swing.JMenuBar jMenuBar6;
    private javax.swing.JMenuBar jMenuBar7;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel jlabel_usuario;
    private javax.swing.JMenuItem jm_acesso;
    private javax.swing.JMenu jm_caixa;
    private javax.swing.JMenuItem jm_conf_impressora;
    private javax.swing.JMenu jm_consulta;
    private javax.swing.JMenuItem jm_usuario;
    private javax.swing.JMenuItem jmi_atendimento_devolucao;
    private javax.swing.JMenuItem jmi_atendimento_locacao;
    private javax.swing.JMenuItem jmi_atendimento_venda;
    private javax.swing.JMenuItem jmi_backup;
    private javax.swing.JMenuItem jmi_cliente;
    private javax.swing.JMenuItem jmi_diaria;
    private javax.swing.JMenuItem jmi_fornecedor;
    private javax.swing.JMenuItem jmi_genero;
    private javax.swing.JMenuItem jmi_gerar_codigo_barras;
    private javax.swing.JMenuItem jmi_idioma;
    private javax.swing.JMenuItem jmi_legenda;
    private javax.swing.JMenuItem jmi_objeto;
    private javax.swing.JMenuItem jmi_objeto_copia;
    private javax.swing.JMenuItem jmi_pacote_promocional;
    private javax.swing.JMenuItem jmi_pagar_receber;
    private javax.swing.JMenuItem jmi_produto;
    private javax.swing.JLabel label_data;
    private javax.swing.JMenu menu_cadastros;
    private javax.swing.JMenu menu_movimentos;
    private javax.swing.JMenu menu_movimentos2;
    private javax.swing.JMenu menu_relatórios;
    private javax.swing.JMenu menu_relatórios1;
    private javax.swing.JMenu menu_relatórios2;
    private javax.swing.JMenuItem menuitem_sair;
    // End of variables declaration//GEN-END:variables

    public void setStatusTela(boolean status) {
        if (status) {
            this.setVisible(status);
        }
        this.setEnabled(status);
    }

    public void carregaUsuario(Usuario usuario) {
        if (usuario != null) {
            TelaPrincipal.usuario = usuario;
            jlabel_usuario.setText("Usuário: " + usuario.getNome_usuario());
        } else {
            JOptionPane.showMessageDialog(null, "Usuário não foi carregado com sucesso");
        }
    }

    public void acionarAtalho(java.awt.event.KeyEvent evt) {

        if (evt.getKeyCode() == KeyEvent.VK_F2) {
            jmi_atendimento_locacao.doClick();
        }
        if (evt.getKeyCode() == KeyEvent.VK_F3) {
            jmi_atendimento_devolucao.doClick();
        }
        if (evt.getKeyCode() == KeyEvent.VK_F4) {
            jmi_atendimento_venda.doClick();
        }
        if (evt.getKeyCode() == KeyEvent.VK_F6) {
            jmi_objeto_copia.doClick();
        }
    }

}
